/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param futureInstallmentAllocationRule
 * @param paymentAllocationOrder
 * @param transactionType
 */

@Serializable
data class AdvancedPaymentData(

    val futureInstallmentAllocationRule: kotlin.String? = null,

    val paymentAllocationOrder: kotlin.collections.List<PaymentAllocationOrder>? = null,

    val transactionType: kotlin.String? = null

)

