/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param columnFilters
 * @param nonNullFilters
 * @param nonNullResultColumns
 * @param resultColumns
 */

@Serializable
data class AdvancedQueryData(

    val columnFilters: kotlin.collections.List<ColumnFilterData>? = null,

    val nonNullFilters: kotlin.collections.List<ColumnFilterData>? = null,

    val nonNullResultColumns: kotlin.collections.List<kotlin.String>? = null,

    val resultColumns: kotlin.collections.List<kotlin.String>? = null

)

