/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param clients
 * @param rowIndex
 * @param selfServiceUser
 */

@Serializable
data class AppUserData(

    val clients: kotlin.collections.Set<ClientData>? = null,

    val rowIndex: kotlin.Int? = null,

    val selfServiceUser: kotlin.Boolean? = null

)

