/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.time.LocalDate

/**
 *
 *
 * @param accountNonExpired
 * @param accountNonLocked
 * @param appUserClientMappings
 * @param authorities
 * @param bypassUser
 * @param credentialsNonExpired
 * @param deleted
 * @param displayName
 * @param email
 * @param enabled
 * @param firstname
 * @param id
 * @param lastTimePasswordUpdated
 * @param lastname
 * @param new
 * @param notEnabled
 * @param office
 * @param password
 * @param passwordNeverExpires
 * @param roles
 * @param selfServiceUser
 * @param staff
 * @param staffDisplayName
 * @param staffId
 * @param systemUser
 * @param username
 */

@Serializable
data class AppUser(

    val accountNonExpired: kotlin.Boolean? = null,

    val accountNonLocked: kotlin.Boolean? = null,

    val appUserClientMappings: kotlin.collections.Set<AppUserClientMapping>? = null,

    val authorities: kotlin.collections.List<GrantedAuthority>? = null,

    val bypassUser: kotlin.Boolean? = null,

    val credentialsNonExpired: kotlin.Boolean? = null,

    val deleted: kotlin.Boolean? = null,

    val displayName: kotlin.String? = null,

    val email: kotlin.String? = null,

    val enabled: kotlin.Boolean? = null,

    val firstname: kotlin.String? = null,

    val id: kotlin.Long? = null,

    @Contextual
    val lastTimePasswordUpdated: LocalDate? = null,

    val lastname: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    val notEnabled: kotlin.Boolean? = null,

    val office: Office? = null,

    val password: kotlin.String? = null,

    val passwordNeverExpires: kotlin.Boolean? = null,

    val roles: kotlin.collections.Set<Role>? = null,

    val selfServiceUser: kotlin.Boolean? = null,

    val staff: Staff? = null,

    val staffDisplayName: kotlin.String? = null,

    val staffId: kotlin.Long? = null,

    val systemUser: kotlin.Boolean? = null,

    val username: kotlin.String? = null

)

