/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param contentDisposition
 * @param entity
 * @param headers
 * @param mediaType
 * @param messageBodyWorkers
 * @param parameterizedHeaders
 * @param parent
 * @param providers
 */

@Serializable
data class BodyPart(

    val contentDisposition: ContentDisposition? = null,

    @Contextual
    val entity: kotlin.Any? = null,

    val headers: BodyPartHeaders? = null,

    val mediaType: MediaType? = null,

    @Contextual
    val messageBodyWorkers: kotlin.Any? = null,

    val parameterizedHeaders: BodyPartParameterizedHeaders? = null,

    val parent: MultiPart? = null,

    @Contextual
    val providers: kotlin.Any? = null

)

