/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * BusinessStep
 *
 * @param order
 * @param stepName
 */

@Serializable
data class BusinessStep(

    val order: kotlin.Long? = null,

    val stepName: kotlin.String? = null

)

