/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNo
 * @param collectionMeetingCalendar
 * @param datatables
 * @param hierarchy
 * @param id
 * @param name
 * @param officeName
 * @param rowIndex
 * @param staffName
 */

@Serializable
data class CenterData(

    val accountNo: kotlin.String? = null,

    val collectionMeetingCalendar: CalendarData? = null,

    val datatables: kotlin.collections.List<DatatableData>? = null,

    val hierarchy: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val officeName: kotlin.String? = null,

    val rowIndex: kotlin.Int? = null,

    val staffName: kotlin.String? = null

)

