/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param age
 * @param clientId
 * @param dateOfBirth
 * @param firstName
 * @param gender
 * @param genderId
 * @param id
 * @param isDependent
 * @param lastName
 * @param maritalStatus
 * @param maritalStatusId
 * @param middleName
 * @param mobileNumber
 * @param profession
 * @param professionId
 * @param qualification
 * @param relationship
 * @param relationshipId
 */

@Serializable
data class ClientFamilyMembersData(

    val age: kotlin.Long? = null,

    val clientId: kotlin.Long? = null,

    @Contextual
    val dateOfBirth: java.time.LocalDate? = null,

    val firstName: kotlin.String? = null,

    val gender: kotlin.String? = null,

    val genderId: kotlin.Long? = null,

    val id: kotlin.Long? = null,

    val isDependent: kotlin.Boolean? = null,

    val lastName: kotlin.String? = null,

    val maritalStatus: kotlin.String? = null,

    val maritalStatusId: kotlin.Long? = null,

    val middleName: kotlin.String? = null,

    val mobileNumber: kotlin.String? = null,

    val profession: kotlin.String? = null,

    val professionId: kotlin.Long? = null,

    val qualification: kotlin.String? = null,

    val relationship: kotlin.String? = null,

    val relationshipId: kotlin.Long? = null

)

