/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.time.LocalDate

/**
 *
 *
 * @param createdBy
 * @param createdDate
 * @param createdDateTime
 * @param lastModifiedBy
 * @param lastModifiedDate
 * @param lastModifiedDateTime
 * @param accountNumber
 * @param accountNumberRequiresAutoGeneration
 * @param activatedBy
 * @param activationDate
 * @param active
 * @param clientClassification
 * @param clientType
 * @param closed
 * @param closedBy
 * @param closureDate
 * @param closureReason
 * @param dateOfBirth
 * @param displayName
 * @param emailAddress
 * @param externalId
 * @param firstname
 * @param fullname
 * @param gender
 * @param groups
 * @param id
 * @param image
 * @param lastname
 * @param legalForm
 * @param middlename
 * @param mobileNo
 * @param new
 * @param notActive
 * @param notPending
 * @param notStaff
 * @param office
 * @param officeJoiningDate
 * @param pending
 * @param proposedTransferDate
 * @param reactivateDate
 * @param reactivatedBy
 * @param rejected
 * @param rejectedBy
 * @param rejectedDate
 * @param rejectionDate
 * @param rejectionReason
 * @param reopenedBy
 * @param reopenedDate
 * @param savingsAccountId
 * @param savingsProductId
 * @param staff
 * @param status
 * @param subStatus
 * @param submittedOnDate
 * @param transferInProgress
 * @param transferInProgressOrOnHold
 * @param transferOnHold
 * @param transferToOffice
 * @param withdrawalDate
 * @param withdrawalReason
 * @param withdrawn
 * @param withdrawnBy
 */

@Serializable
data class Client(

    val createdBy: kotlin.Long,

    @Contextual
    val createdDate: java.time.OffsetDateTime,

    @Contextual
    val createdDateTime: java.time.OffsetDateTime,

    val lastModifiedBy: kotlin.Long,

    @Contextual
    val lastModifiedDate: java.time.OffsetDateTime,

    @Contextual
    val lastModifiedDateTime: java.time.OffsetDateTime,

    val accountNumber: kotlin.String? = null,

    val accountNumberRequiresAutoGeneration: kotlin.Boolean? = null,

    val activatedBy: AppUser? = null,

    @Contextual
    val activationDate: java.time.LocalDate? = null,

    val active: kotlin.Boolean? = null,

    val clientClassification: CodeValue? = null,

    val clientType: CodeValue? = null,

    val closed: kotlin.Boolean? = null,

    val closedBy: AppUser? = null,

    @Contextual
    val closureDate: java.time.LocalDate? = null,

    val closureReason: CodeValue? = null,

    @Contextual
    val dateOfBirth: java.time.LocalDate? = null,

    val displayName: kotlin.String? = null,

    val emailAddress: kotlin.String? = null,

    val externalId: ExternalId? = null,

    val firstname: kotlin.String? = null,

    val fullname: kotlin.String? = null,

    val gender: CodeValue? = null,

    val groups: kotlin.collections.Set<Group>? = null,

    val id: kotlin.Long? = null,

    val image: Image? = null,

    val lastname: kotlin.String? = null,

    val legalForm: kotlin.Int? = null,

    val middlename: kotlin.String? = null,

    val mobileNo: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    val notActive: kotlin.Boolean? = null,

    val notPending: kotlin.Boolean? = null,

    val notStaff: kotlin.Boolean? = null,

    val office: Office? = null,

    @Contextual
    val officeJoiningDate: java.time.LocalDate? = null,

    val pending: kotlin.Boolean? = null,

    @Contextual
    val proposedTransferDate: java.time.LocalDate? = null,

    @Contextual
    val reactivateDate: java.time.LocalDate? = null,

    val reactivatedBy: AppUser? = null,

    val rejected: kotlin.Boolean? = null,

    val rejectedBy: AppUser? = null,

    @Contextual
    val rejectedDate: java.time.LocalDate? = null,

    @Contextual
    val rejectionDate: java.time.LocalDate? = null,

    val rejectionReason: CodeValue? = null,

    val reopenedBy: AppUser? = null,

    @Contextual
    val reopenedDate: LocalDate? = null,

    val savingsAccountId: kotlin.Long? = null,

    val savingsProductId: kotlin.Long? = null,

    val staff: Staff? = null,

    val status: kotlin.Int? = null,

    val subStatus: CodeValue? = null,

    @Contextual
    val submittedOnDate: LocalDate? = null,

    val transferInProgress: kotlin.Boolean? = null,

    val transferInProgressOrOnHold: kotlin.Boolean? = null,

    val transferOnHold: kotlin.Boolean? = null,

    val transferToOffice: Office? = null,

    @Contextual
    val withdrawalDate: LocalDate? = null,

    val withdrawalReason: CodeValue? = null,

    val withdrawn: kotlin.Boolean? = null,

    val withdrawnBy: AppUser? = null

)

