/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param description
 * @param id
 * @param mandatory
 * @param name
 * @param position
 */

@Serializable
data class CodeValueData(

    val active: kotlin.Boolean? = null,

    val description: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val mandatory: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val position: kotlin.Int? = null

)

