/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * DeleteSavingsAccountsAccountIdResponse
 *
 * @param clientId
 * @param officeId
 * @param resourceId
 */

@Serializable
data class DeleteSavingsAccountsAccountIdResponse(

    val clientId: kotlin.Int? = null,

    val officeId: kotlin.Int? = null,

    val resourceId: kotlin.Int? = null

)

