/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param journalEntryData
 * @param ownerData
 */

@Serializable
data class ExternalOwnerJournalEntryData(

    val journalEntryData: PageJournalEntryData? = null,

    val ownerData: ExternalTransferOwnerData? = null

)

