/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param details
 * @param effectiveFrom
 * @param effectiveTo
 * @param loan
 * @param owner
 * @param purchasePriceRatio
 * @param settlementDate
 * @param status
 * @param subStatus
 * @param transferExternalId
 * @param transferId
 */

@Serializable
data class ExternalTransferData(

    val details: ExternalTransferDataDetails? = null,

    @Contextual
    val effectiveFrom: java.time.LocalDate? = null,

    @Contextual
    val effectiveTo: java.time.LocalDate? = null,

    val loan: ExternalTransferLoanData? = null,

    val owner: ExternalTransferOwnerData? = null,

    val purchasePriceRatio: kotlin.String? = null,

    @Contextual
    val settlementDate: java.time.LocalDate? = null,

    val status: ExternalTransferData.Status? = null,

    val subStatus: ExternalTransferData.SubStatus? = null,

    val transferExternalId: kotlin.String? = null,

    val transferId: kotlin.Long? = null

) {

    /**
     *
     *
     * Values: ACTIVE,DECLINED,PENDING,BUYBACK,CANCELLED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "ACTIVE")
        ACTIVE("ACTIVE"),
        @Json(name = "DECLINED")
        DECLINED("DECLINED"),
        @Json(name = "PENDING")
        PENDING("PENDING"),
        @Json(name = "BUYBACK")
        BUYBACK("BUYBACK"),
        @Json(name = "CANCELLED")
        CANCELLED("CANCELLED");
    }

    /**
     *
     *
     * Values: BALANCE_ZERO,BALANCE_NEGATIVE,SAMEDAY_TRANSFERS,USER_REQUESTED,UNSOLD
     */
    @JsonClass(generateAdapter = false)
    enum class SubStatus(val value: kotlin.String) {
        @Json(name = "BALANCE_ZERO")
        BALANCE_ZERO("BALANCE_ZERO"),
        @Json(name = "BALANCE_NEGATIVE")
        BALANCE_NEGATIVE("BALANCE_NEGATIVE"),
        @Json(name = "SAMEDAY_TRANSFERS")
        SAMEDAY_TRANSFERS("SAMEDAY_TRANSFERS"),
        @Json(name = "USER_REQUESTED")
        USER_REQUESTED("USER_REQUESTED"),
        @Json(name = "UNSOLD")
        UNSOLD("UNSOLD");
    }

}

