/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * ExternalAssetOwnerTransferChangesData
 *
 * @param ownerExternalId
 * @param purchasePriceRatio
 * @param settlementDate
 * @param transferExternalId
 */

@Serializable
data class ExternalAssetOwnerTransferChangesData(

    val ownerExternalId: kotlin.String? = null,

    val purchasePriceRatio: kotlin.String? = null,

    @Contextual
    val settlementDate: java.time.LocalDate? = null,

    val transferExternalId: kotlin.String? = null

)

