/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param createdBy
 * @param createdOn
 * @param differentialToBaseLendingRate
 * @param fromDate
 * @param fromDateAsLocalDate
 * @param id
 * @param interestRate
 * @param modifiedBy
 * @param modifiedOn
 */

@Serializable
data class FloatingRatePeriodData(

    val active: kotlin.Boolean? = null,

    val createdBy: kotlin.String? = null,

    @Contextual
    val createdOn: java.time.OffsetDateTime? = null,

    val differentialToBaseLendingRate: kotlin.Boolean? = null,

    @Contextual
    val fromDate: java.time.LocalDate? = null,

    @Contextual
    val fromDateAsLocalDate: java.time.LocalDate? = null,

    val id: kotlin.Long? = null,

    @Contextual
    val interestRate: java.math.BigDecimal? = null,

    val modifiedBy: kotlin.String? = null,

    @Contextual
    val modifiedOn: java.time.OffsetDateTime? = null

)

