/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param createdBy
 * @param createdDate
 * @param createdDateTime
 * @param lastModifiedBy
 * @param lastModifiedDate
 * @param lastModifiedDateTime
 * @param active
 * @param baseLendingRate
 * @param floatingRatePeriods
 * @param id
 * @param name
 * @param new
 */

@Serializable
data class FloatingRate(

    val createdBy: kotlin.Long,

    @Contextual
    val createdDate: java.time.OffsetDateTime,

    @Contextual
    val createdDateTime: java.time.OffsetDateTime,

    val lastModifiedBy: kotlin.Long,

    @Contextual
    val lastModifiedDate: java.time.OffsetDateTime,

    @Contextual
    val lastModifiedDateTime: java.time.OffsetDateTime,

    val active: kotlin.Boolean? = null,

    val baseLendingRate: kotlin.Boolean? = null,

    val floatingRatePeriods: kotlin.collections.List<FloatingRatePeriod>? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val new: kotlin.Boolean? = null

)

