/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param baseLendingRate
 * @param createdBy
 * @param createdOn
 * @param id
 * @param modifiedBy
 * @param modifiedOn
 * @param name
 * @param ratePeriods
 */

@Serializable
data class FloatingRateData(

    val active: kotlin.Boolean? = null,

    val baseLendingRate: kotlin.Boolean? = null,

    val createdBy: kotlin.String? = null,

    @Contextual
    val createdOn: java.time.OffsetDateTime? = null,

    val id: kotlin.Long? = null,

    val modifiedBy: kotlin.String? = null,

    @Contextual
    val modifiedOn: java.time.OffsetDateTime? = null,

    val name: kotlin.String? = null,

    val ratePeriods: kotlin.collections.List<FloatingRatePeriodData>? = null

)

