/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param createdBy
 * @param createdDate
 * @param createdDateTime
 * @param lastModifiedBy
 * @param lastModifiedDate
 * @param lastModifiedDateTime
 * @param active
 * @param differentialToBaseLendingRate
 * @param floatingRate
 * @param fromDate
 * @param id
 * @param interestRate
 * @param new
 */

@Serializable
data class FloatingRatePeriod(

    val createdBy: kotlin.Long,

    @Contextual
    val createdDate: java.time.OffsetDateTime,

    @Contextual
    val createdDateTime: java.time.OffsetDateTime,

    val lastModifiedBy: kotlin.Long,

    @Contextual
    val lastModifiedDate: java.time.OffsetDateTime,

    @Contextual
    val lastModifiedDateTime: java.time.OffsetDateTime,

    val active: kotlin.Boolean? = null,

    val differentialToBaseLendingRate: kotlin.Boolean? = null,

    val floatingRate: FloatingRate? = null,

    @Contextual
    val fromDate: java.time.LocalDate? = null,

    val id: kotlin.Long? = null,

    @Contextual
    val interestRate: java.math.BigDecimal? = null,

    val new: kotlin.Boolean? = null

)

