/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param content
 * @param contentDisposition
 * @param entity
 * @param fileName
 * @param formDataContentDisposition
 * @param headers
 * @param mediaType
 * @param messageBodyWorkers
 * @param name
 * @param parameterizedHeaders
 * @param parent
 * @param providers
 * @param simple
 * @param `value`
 */

@Serializable
data class FormDataBodyPart(

    @Contextual
    val content: kotlin.Any? = null,

    val contentDisposition: ContentDisposition? = null,

    @Contextual
    val entity: kotlin.Any? = null,

    val fileName: kotlin.String? = null,

    val formDataContentDisposition: FormDataContentDisposition? = null,

    val headers: BodyPartHeaders? = null,

    val mediaType: MediaType? = null,

    @Contextual
    val messageBodyWorkers: kotlin.Any? = null,

    val name: kotlin.String? = null,

    val parameterizedHeaders: BodyPartParameterizedHeaders? = null,

    val parent: MultiPart? = null,

    @Contextual
    val providers: kotlin.Any? = null,

    val simple: kotlin.Boolean? = null,

    val value: kotlin.String? = null

)

