/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNo
 * @param activationDate
 * @param active
 * @param clientClassification
 * @param clientType
 * @param displayName
 * @param firstname
 * @param gender
 * @param groups
 * @param id
 * @param lastname
 * @param officeId
 * @param officeName
 * @param status
 * @param timeline
 */

@Serializable
data class GetAccountTransfersTemplateRefundByTransferFromClient(

    val accountNo: kotlin.Long? = null,

    @Contextual
    val activationDate: java.time.LocalDate? = null,

    val active: kotlin.Boolean? = null,

    @Contextual
    val clientClassification: kotlin.Any? = null,

    @Contextual
    val clientType: kotlin.Any? = null,

    val displayName: kotlin.String? = null,

    val firstname: kotlin.String? = null,

    @Contextual
    val gender: kotlin.Any? = null,

    @Contextual
    val groups: kotlin.Any? = null,

    val id: kotlin.Long? = null,

    val lastname: kotlin.String? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    val status: GetAccountTransfersStatus? = null,

    val timeline: GetAccountTransfersTimeline? = null

)

