/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetAccountsLinkedToPocketResponse
 *
 * @param loanAccounts
 * @param savingAccounts
 * @param shareAccounts
 */

@Serializable
data class GetAccountsLinkedToPocketResponse(

    val loanAccounts: kotlin.collections.Set<GetPocketLoanAccounts>? = null,

    val savingAccounts: kotlin.collections.Set<GetPocketSavingAccounts>? = null,

    val shareAccounts: kotlin.collections.Set<@Contextual kotlin.Any>? = null

)

