/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param currency
 * @param fromAccount
 * @param fromAccountType
 * @param fromClient
 * @param fromOffice
 * @param id
 * @param reversed
 * @param toAccount
 * @param toAccountType
 * @param toClient
 * @param toOffice
 * @param transferAmount
 * @param transferDate
 * @param transferDescription
 */

@Serializable
data class GetAccountTransfersPageItems(

    val currency: GetAccountTransfersPageItemsCurrency? = null,

    val fromAccount: GetAccountTransfersPageItemsFromAccount? = null,

    val fromAccountType: GetAccountTransfersFromAccountType? = null,

    val fromClient: GetAccountTransfersFromClientOptions? = null,

    val fromOffice: GetAccountTransfersPageItemsFromOffice? = null,

    val id: kotlin.Long? = null,

    val reversed: kotlin.Boolean? = null,

    val toAccount: GetAccountTransfersPageItemsFromAccount? = null,

    val toAccountType: GetAccountTransfersPageItemsToAccountType? = null,

    val toClient: GetAccountTransfersFromClientOptions? = null,

    val toOffice: GetAccountTransfersPageItemsFromOffice? = null,

    val transferAmount: kotlin.Float? = null,

    @Contextual
    val transferDate: java.time.LocalDate? = null,

    val transferDescription: kotlin.String? = null

)

