/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetAccountsChargesCurrency
import org.openapitools.client.models.GetAccountsTypePurchasedShares
import org.openapitools.client.models.GetAccountsTypeStatus
import org.openapitools.client.models.GetAccountsTypeSummary
import org.openapitools.client.models.GetAccountsTypeTimeline

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param accountNo 
 * @param clientId 
 * @param clientName 
 * @param currency 
 * @param id 
 * @param productId 
 * @param productName 
 * @param purchasedShares 
 * @param status 
 * @param summary 
 * @param timeline 
 */

@Serializable
data class GetAccountsPageItems (

    val accountNo: kotlin.Long? = null,

    val clientId: kotlin.Long? = null,

    val clientName: kotlin.String? = null,

    val currency: GetAccountsChargesCurrency? = null,

    val id: kotlin.Long? = null,

    val productId: kotlin.Long? = null,

    val productName: kotlin.String? = null,

    val purchasedShares: kotlin.collections.Set<GetAccountsTypePurchasedShares>? = null,

    val status: GetAccountsTypeStatus? = null,

    val summary: GetAccountsTypeSummary? = null,

    val timeline: GetAccountsTypeTimeline? = null

) {


}

