/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountId
 * @param amount
 * @param amountPaid
 * @param chargeAmount
 * @param id
 * @param numberOfShares
 * @param purchasedDate
 * @param purchasedPrice
 * @param status
 * @param type
 */

@Serializable
data class GetAccountsPurchasedShares(

    val accountId: kotlin.Long? = null,

    val amount: kotlin.Double? = null,

    val amountPaid: kotlin.Double? = null,

    val chargeAmount: kotlin.Double? = null,

    val id: kotlin.Long? = null,

    val numberOfShares: kotlin.Int? = null,

    @Contextual
    val purchasedDate: java.time.LocalDate? = null,

    val purchasedPrice: kotlin.Double? = null,

    val status: GetAccountsPurchasedSharesStatus? = null,

    val type: GetAccountsPurchasedSharesType? = null

)

