/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetAccountRulesTemplateResponse
 *
 * @param allowedAccounts
 * @param allowedOffices
 * @param systemDefined
 */

@Serializable
data class GetAccountRulesTemplateResponse(

    val allowedAccounts: kotlin.collections.List<GLAccountData>? = null,

    val allowedOffices: kotlin.collections.List<OfficeData>? = null,

    val systemDefined: kotlin.Boolean? = null

)

