/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetBusinessStepConfigResponse
 *
 * @param businessSteps
 * @param jobName
 */

@Serializable
data class GetBusinessStepConfigResponse(

    val businessSteps: kotlin.collections.List<BusinessStep>? = null,

    val jobName: kotlin.String? = null

)

