/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetChargesResponse
 *
 * @param active
 * @param amount
 * @param chargeAppliesTo
 * @param chargeCalculationType
 * @param chargePaymentMode
 * @param chargeTimeType
 * @param currency
 * @param id
 * @param name
 * @param penalty
 */

@Serializable
data class GetChargesResponse(

    val active: kotlin.Boolean? = null,

    val amount: kotlin.Double? = null,

    val chargeAppliesTo: GetChargesAppliesToResponse? = null,

    val chargeCalculationType: GetChargesCalculationTypeResponse? = null,

    val chargePaymentMode: GetChargesPaymentModeResponse? = null,

    val chargeTimeType: GetChargesTimeTypeResponse? = null,

    val currency: GetChargesCurrencyResponse? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val penalty: kotlin.Boolean? = null

)

