/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetClientsClientIdIdentifiersResponse
 *
 * @param clientId
 * @param description
 * @param documentKey
 * @param documentType
 * @param id
 */

@Serializable
data class GetClientsClientIdIdentifiersResponse(

    val clientId: kotlin.Long? = null,

    val description: kotlin.String? = null,

    val documentKey: kotlin.String? = null,

    val documentType: GetClientsDocumentType? = null,

    val id: kotlin.Long? = null

)

