/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param amount
 * @param currency
 * @param date
 * @param id
 * @param officeId
 * @param officeName
 * @param reversed
 * @param submittedOnDate
 * @param type
 */

@Serializable
data class GetClientsPageItems(

    val amount: kotlin.Double? = null,

    val currency: GetClientTransactionsCurrency? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val id: kotlin.Long? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    val reversed: kotlin.Boolean? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null,

    val type: GetClientsClientIdTransactionsType? = null

)

