/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetCentersTemplateResponse
 *
 * @param activationDate
 * @param active
 * @param officeId
 * @param officeOptions
 * @param staffOptions
 */

@Serializable
data class GetCentersTemplateResponse(

    @Contextual
    val activationDate: java.time.LocalDate? = null,

    val active: kotlin.Boolean? = null,

    val officeId: kotlin.Long? = null,

    val officeOptions: kotlin.collections.Set<GetCentersOfficeOptions>? = null,

    val staffOptions: kotlin.collections.Set<GetCentersStaffOptions>? = null

)

