/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetCurrenciesResponse
 *
 * @param currencyOptions
 * @param selectedCurrencyOptions
 */

@Serializable
data class GetCurrenciesResponse(

    val currencyOptions: kotlin.collections.List<CurrencyData>? = null,

    val selectedCurrencyOptions: kotlin.collections.List<CurrencyData>? = null

)

