/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * GetDelinquencyRangesResponse
 *
 * @param classification
 * @param id
 * @param maximumAgeDays
 * @param minimumAgeDays
 */

@Serializable
data class GetDelinquencyRangesResponse(

    val classification: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val maximumAgeDays: kotlin.Int? = null,

    val minimumAgeDays: kotlin.Int? = null

)

