/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetExternalEventConfigurationsResponse
 *
 * @param externalEventConfiguration
 */

@Serializable
data class GetExternalEventConfigurationsResponse(

    val externalEventConfiguration: kotlin.collections.List<ExternalEventConfigurationItemData>? = null

)

