/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param glCode
 * @param id
 * @param name
 */

@Serializable
data class GetFixedDepositProductsProductIdSavingsControlAccount(

    val glCode: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null

)

