/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetFixedDepositAccountsAccountIdResponse
 *
 * @param accountChart
 * @param accountNo
 * @param clientId
 * @param clientName
 * @param currency
 * @param depositAmount
 * @param depositPeriod
 * @param depositPeriodFrequency
 * @param externalId
 * @param fieldOfficerId
 * @param id
 * @param interestCalculationDaysInYearType
 * @param interestCalculationType
 * @param interestCompoundingPeriodType
 * @param interestFreePeriodApplicable
 * @param interestPostingPeriodType
 * @param maturityAmount
 * @param maturityDate
 * @param maxDepositTerm
 * @param maxDepositTermType
 * @param minDepositTerm
 * @param minDepositTermType
 * @param preClosurePenalApplicable
 * @param savingsProductId
 * @param savingsProductName
 * @param status
 * @param summary
 * @param timeline
 */

@Serializable
data class GetFixedDepositAccountsAccountIdResponse(

    val accountChart: GetFixedDepositAccountsAccountChart? = null,

    val accountNo: kotlin.Long? = null,

    val clientId: kotlin.Long? = null,

    val clientName: kotlin.String? = null,

    val currency: GetFixedDepositAccountsAccountIdCurrency? = null,

    val depositAmount: kotlin.Float? = null,

    val depositPeriod: kotlin.Int? = null,

    val depositPeriodFrequency: GetFixedDepositAccountsDepositPeriodFrequency? = null,

    val externalId: kotlin.String? = null,

    val fieldOfficerId: kotlin.Long? = null,

    val id: kotlin.Long? = null,

    val interestCalculationDaysInYearType: GetFixedDepositAccountsInterestCalculationDaysInYearType? = null,

    val interestCalculationType: GetFixedDepositAccountsInterestCalculationType? = null,

    val interestCompoundingPeriodType: GetFixedDepositAccountsInterestCompoundingPeriodType? = null,

    val interestFreePeriodApplicable: kotlin.Boolean? = null,

    val interestPostingPeriodType: GetFixedDepositAccountsInterestPostingPeriodType? = null,

    val maturityAmount: kotlin.Float? = null,

    @Contextual
    val maturityDate: java.time.LocalDate? = null,

    val maxDepositTerm: kotlin.Int? = null,

    val maxDepositTermType: GetFixedDepositAccountsMaxDepositTermType? = null,

    val minDepositTerm: kotlin.Int? = null,

    val minDepositTermType: GetFixedDepositAccountsMinDepositTermType? = null,

    val preClosurePenalApplicable: kotlin.Boolean? = null,

    val savingsProductId: kotlin.Long? = null,

    val savingsProductName: kotlin.String? = null,

    val status: GetFixedDepositAccountsStatus? = null,

    val summary: GetFixedDepositAccountsAccountIdSummary? = null,

    val timeline: GetFixedDepositAccountsTimeline? = null

)

