/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param incomeFromFeeAccount
 * @param incomeFromPenaltyAccount
 * @param interestOnSavingsAccount
 * @param savingsControlAccount
 * @param savingsReferenceAccount
 * @param transfersInSuspenseAccount
 */

@Serializable
data class GetFixedDepositProductsProductIdAccountingMappings(

    val incomeFromFeeAccount: GetFixedDepositProductsProductIdIncomeFromFeeAccount? = null,

    val incomeFromPenaltyAccount: GetFixedDepositProductsProductIdIncomeFromPenaltyAccount? = null,

    val interestOnSavingsAccount: GetFixedDepositProductsProductIdInterestOnSavingsAccount? = null,

    val savingsControlAccount: GetFixedDepositProductsProductIdSavingsControlAccount? = null,

    val savingsReferenceAccount: GetFixedDepositProductsProductIdSavingsReferenceAccount? = null,

    val transfersInSuspenseAccount: GetFixedDepositProductsProductIdTransfersInSuspenseAccount? = null

)

