/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * GetFieldConfigurationEntityResponse
 *
 * @param entity
 * @param `field`
 * @param fieldConfigurationId
 * @param isEnabled
 * @param isMandatory
 * @param subentity
 * @param validationRegex
 */

@Serializable
data class GetFieldConfigurationEntityResponse(

    val entity: kotlin.String? = null,

    val field: kotlin.String? = null,

    val fieldConfigurationId: kotlin.Long? = null,

    val is_enabled: kotlin.String? = null,

    val is_mandatory: kotlin.String? = null,

    val subentity: kotlin.String? = null,

    val validation_regex: kotlin.String? = null

)

