/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountBalance
 * @param currency
 */

@Serializable
data class GetFixedDepositAccountsSummary(

    val accountBalance: kotlin.Float? = null,

    val currency: GetFixedDepositAccountsCurrency? = null

)

