/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param createdBy
 * @param createdOn
 * @param fromDate
 * @param id
 * @param interestRate
 * @param isActive
 * @param isDifferentialToBaseLendingRate
 * @param modifiedBy
 * @param modifiedOn
 */

@Serializable
data class GetFloatingRatesRatePeriods(

    val createdBy: kotlin.String? = null,

    val createdOn: kotlin.String? = null,

    val fromDate: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val interestRate: kotlin.Double? = null,

    val isActive: kotlin.Boolean? = null,

    val isDifferentialToBaseLendingRate: kotlin.Boolean? = null,

    val modifiedBy: kotlin.String? = null,

    val modifiedOn: kotlin.String? = null

)

