/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetGLAccountsResponse
 *
 * @param description
 * @param disabled
 * @param glCode
 * @param id
 * @param manualEntriesAllowed
 * @param name
 * @param nameDecorated
 * @param organizationRunningBalance
 * @param parentId
 * @param tagId
 * @param type
 * @param usage
 */

@Serializable
data class GetGLAccountsResponse(

    val description: kotlin.String? = null,

    val disabled: kotlin.Boolean? = null,

    val glCode: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val manualEntriesAllowed: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val nameDecorated: kotlin.String? = null,

    val organizationRunningBalance: kotlin.Long? = null,

    val parentId: kotlin.Long? = null,

    val tagId: CodeValueData? = null,

    val type: EnumOptionData? = null,

    val usage: EnumOptionData? = null

)

