/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param columnDisplayType
 * @param columnLength
 * @param columnName
 * @param columnType
 * @param columnValues
 * @param isColumnNullable
 * @param isColumnPrimaryKey
 */

@Serializable
data class GetGroupsTemplateColumnHeaderData(

    val columnDisplayType: kotlin.String? = null,

    val columnLength: kotlin.Int? = null,

    val columnName: kotlin.String? = null,

    val columnType: kotlin.String? = null,

    val columnValues: kotlin.collections.Set<@Contextual kotlin.Any>? = null,

    val isColumnNullable: kotlin.Boolean? = null,

    val isColumnPrimaryKey: kotlin.Boolean? = null

)

