/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetGroupsGroupIdResponse
 *
 * @param externalId
 * @param hierarchy
 * @param id
 * @param name
 * @param officeId
 * @param officeName
 * @param timeline
 */

@Serializable
data class GetGroupsGroupIdResponse(

    val externalId: kotlin.String? = null,

    val hierarchy: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    val timeline: GetGroupsGroupIdTimeline? = null

)

