/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetGroupsTemplateResponse
 *
 * @param clientOptions
 * @param datatables
 * @param officeId
 * @param officeOptions
 * @param staffOptions
 */

@Serializable
data class GetGroupsTemplateResponse(

    val clientOptions: kotlin.collections.Set<GetGroupsTemplateClientOptions>? = null,

    val datatables: kotlin.collections.Set<GetGroupsTemplateDatatables>? = null,

    val officeId: kotlin.Long? = null,

    val officeOptions: kotlin.collections.Set<GetGroupsTemplateOfficeOptions>? = null,

    val staffOptions: kotlin.collections.Set<GetGroupsTemplateStaffOptions>? = null

)

