/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetHookResponse
 *
 * @param config
 * @param createdAt
 * @param displayName
 * @param events
 * @param id
 * @param isActive
 * @param name
 * @param templateId
 * @param templateName
 * @param updatedAt
 */

@Serializable
data class GetHookResponse(

    val config: kotlin.collections.List<Field>? = null,

    @Contextual
    val createdAt: java.time.LocalDate? = null,

    val displayName: kotlin.String? = null,

    val events: kotlin.collections.List<Event>? = null,

    val id: kotlin.Long? = null,

    val isActive: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val templateId: kotlin.Long? = null,

    val templateName: kotlin.String? = null,

    @Contextual
    val updatedAt: java.time.LocalDate? = null

)

