/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetInterestRateChartsTemplateResponse
 *
 * @param periodTypes
 */

@Serializable
data class GetInterestRateChartsTemplateResponse(

    val periodTypes: kotlin.collections.Set<GetInterestRateChartsTemplatePeriodTypes>? = null

)

