/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param amount
 * @param attributeName
 * @param attributeValue
 * @param attributeValueDesc
 * @param conditionType
 * @param entityType
 * @param id
 * @param incentiveType
 */

@Serializable
data class GetInterestRateChartsChartIdChartSlabsIncentives(

    val amount: kotlin.Float? = null,

    val attributeName: GetInterestRateChartsChartIdChartSlabsAttributeName? = null,

    val attributeValue: kotlin.Int? = null,

    val attributeValueDesc: kotlin.String? = null,

    val conditionType: GetInterestRateChartsChartIdChartSlabsConditionType? = null,

    val entityType: GetInterestRateChartsChartIdChartSlabsEntityType? = null,

    val id: kotlin.Long? = null,

    val incentiveType: GetInterestRateChartsChartIdChartSlabsIncentiveType? = null

)

