/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param interestRecalculationCompoundingFrequencyType
 * @param interestRecalculationCompoundingType
 * @param isArrearsBasedOnOriginalSchedule
 * @param preClosureInterestCalculationStrategy
 * @param productId
 * @param recalculationCompoundingFrequencyInterval
 * @param recalculationCompoundingFrequencyOnDayType
 * @param recalculationRestFrequencyInterval
 * @param recalculationRestFrequencyType
 * @param rescheduleStrategyType
 */

@Serializable
data class GetLoanProductsInterestRecalculationData(

    val id: kotlin.Long? = null,

    val interestRecalculationCompoundingFrequencyType: GetLoanProductsInterestRecalculationCompoundingFrequencyType? = null,

    val interestRecalculationCompoundingType: GetLoanProductsInterestRecalculationCompoundingType? = null,

    val isArrearsBasedOnOriginalSchedule: kotlin.Boolean? = null,

    val preClosureInterestCalculationStrategy: GetLoanProductsPreClosureInterestCalculationStrategy? = null,

    val productId: kotlin.Long? = null,

    val recalculationCompoundingFrequencyInterval: kotlin.Int? = null,

    val recalculationCompoundingFrequencyOnDayType: kotlin.Int? = null,

    val recalculationRestFrequencyInterval: kotlin.Int? = null,

    val recalculationRestFrequencyType: GetLoanProductsInterestRecalculationCompoundingFrequencyType? = null,

    val rescheduleStrategyType: GetLoanProductsRescheduleStrategyType? = null

)

