/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * List of GetLoansLoanIdLoanChargePaidByData
 *
 * @param amount
 * @param chargeId
 * @param id
 * @param installmentNumber
 * @param name
 * @param transactionId
 */

@Serializable
data class GetLoansLoanIdLoanChargePaidByData(

    val amount: kotlin.Double? = null,

    val chargeId: kotlin.Long? = null,

    val id: kotlin.Long? = null,

    val installmentNumber: kotlin.Int? = null,

    val name: kotlin.String? = null,

    val transactionId: kotlin.Long? = null

)

