/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param borrowerCycleNumber
 * @param defaultValue
 * @param id
 * @param maxValue
 * @param minValue
 * @param paramType
 * @param valueConditionType
 */

@Serializable
data class GetLoanProductsPrincipalVariationsForBorrowerCycle(

    val borrowerCycleNumber: kotlin.Int? = null,

    val defaultValue: kotlin.Double? = null,

    val id: kotlin.Long? = null,

    val maxValue: kotlin.Double? = null,

    val minValue: kotlin.Double? = null,

    val paramType: GetLoanProductsParamType? = null,

    val valueConditionType: GetLoanProductsValueConditionType? = null

)

