/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetLoansLoanIdChargesTemplateResponse
 *
 * @param amountPaid
 * @param amountWaived
 * @param amountWrittenOff
 * @param chargeOptions
 * @param penalty
 */

@Serializable
data class GetLoansLoanIdChargesTemplateResponse(

    val amountPaid: kotlin.Double? = null,

    val amountWaived: kotlin.Double? = null,

    val amountWrittenOff: kotlin.Double? = null,

    val chargeOptions: kotlin.collections.Set<GetLoanChargeTemplateChargeOptions>? = null,

    val penalty: kotlin.Boolean? = null

)

