/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param charge
 * @param chargeId
 * @param incomeAccount
 * @param incomeAccountId
 */

@Serializable
data class GetLoanFeeToIncomeAccountMappings(

    val charge: GetLoanCharge? = null,

    val chargeId: kotlin.Long? = null,

    val incomeAccount: GetGlAccountMapping? = null,

    val incomeAccountId: kotlin.Long? = null

)

