/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * Payment detail
 *
 * @param accountNumber
 * @param bankNumber
 * @param checkNumber
 * @param id
 * @param paymentType
 * @param receiptNumber
 * @param routingCode
 */

@Serializable
data class GetLoansLoanIdPaymentDetailData(

    val accountNumber: kotlin.String? = null,

    val bankNumber: kotlin.String? = null,

    val checkNumber: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val paymentType: GetLoansLoanIdPaymentType? = null,

    val receiptNumber: kotlin.String? = null,

    val routingCode: kotlin.String? = null

)

