/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param amount
 * @param chargeAppliesTo
 * @param chargeCalculationType
 * @param chargePaymentMode
 * @param chargeTimeType
 * @param currency
 * @param id
 * @param name
 * @param penalty
 */

@Serializable
data class GetLoanProductsChargeOptions(

    val active: kotlin.Boolean? = null,

    @Contextual
    val amount: java.math.BigDecimal? = null,

    val chargeAppliesTo: GetLoanProductsChargeAppliesTo? = null,

    val chargeCalculationType: GetLoanChargeCalculationType? = null,

    val chargePaymentMode: GetLoansChargePaymentMode? = null,

    val chargeTimeType: GetLoanChargeTimeType? = null,

    val currency: GetLoanProductsCurrencyOptions? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val penalty: kotlin.Boolean? = null

)

