/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param interestRecalculationCompoundingType
 * @param preClosureInterestCalculationStrategy
 * @param rescheduleStrategyType
 */

@Serializable
data class GetLoanProductsInterestRecalculationTemplateData(

    val interestRecalculationCompoundingType: GetLoanProductsInterestRecalculationCompoundingType? = null,

    val preClosureInterestCalculationStrategy: GetLoanProductsPreClosureInterestCalculationStrategy? = null,

    val rescheduleStrategyType: GetLoanProductsRescheduleStrategyType? = null

)

