/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * List of GetLoansLoanIdDelinquencyPausePeriod
 *
 * @param active
 * @param pausePeriodEnd
 * @param pausePeriodStart
 */

@Serializable
data class GetLoansLoanIdDelinquencyPausePeriod(

    val active: kotlin.Boolean? = null,

    @Contextual
    val pausePeriodEnd: java.time.LocalDate? = null,

    @Contextual
    val pausePeriodStart: java.time.LocalDate? = null

)

