/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param actualDisbursementDate
 * @param actualMaturityDate
 * @param approvedByFirstname
 * @param approvedByLastname
 * @param approvedByUsername
 * @param approvedOnDate
 * @param chargedOffByFirstname
 * @param chargedOffByLastname
 * @param chargedOffByUsername
 * @param chargedOffOnDate
 * @param closedOnDate
 * @param disbursedByFirstname
 * @param disbursedByLastname
 * @param disbursedByUsername
 * @param expectedDisbursementDate
 * @param expectedMaturityDate
 * @param submittedByFirstname
 * @param submittedByLastname
 * @param submittedByUsername
 * @param submittedOnDate
 */

@Serializable
data class GetLoansLoanIdTimeline(

    @Contextual
    val actualDisbursementDate: java.time.LocalDate? = null,

    @Contextual
    val actualMaturityDate: java.time.LocalDate? = null,

    val approvedByFirstname: kotlin.String? = null,

    val approvedByLastname: kotlin.String? = null,

    val approvedByUsername: kotlin.String? = null,

    @Contextual
    val approvedOnDate: java.time.LocalDate? = null,

    val chargedOffByFirstname: kotlin.String? = null,

    val chargedOffByLastname: kotlin.String? = null,

    val chargedOffByUsername: kotlin.String? = null,

    @Contextual
    val chargedOffOnDate: java.time.LocalDate? = null,

    @Contextual
    val closedOnDate: java.time.LocalDate? = null,

    val disbursedByFirstname: kotlin.String? = null,

    val disbursedByLastname: kotlin.String? = null,

    val disbursedByUsername: kotlin.String? = null,

    @Contextual
    val expectedDisbursementDate: java.time.LocalDate? = null,

    @Contextual
    val expectedMaturityDate: java.time.LocalDate? = null,

    val submittedByFirstname: kotlin.String? = null,

    val submittedByLastname: kotlin.String? = null,

    val submittedByUsername: kotlin.String? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null

)

