/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetLoansLoanIdTransactionsTransactionIdResponse
 *
 * @param amount
 * @param currency
 * @param date
 * @param externalId
 * @param feeChargesPortion
 * @param id
 * @param interestPortion
 * @param loanChargePaidByList
 * @param manuallyReversed
 * @param netDisbursalAmount
 * @param outstandingLoanBalance
 * @param overpaymentPortion
 * @param paymentDetailData
 * @param penaltyChargesPortion
 * @param possibleNextRepaymentDate
 * @param principalPortion
 * @param reversalExternalId
 * @param reversedOnDate
 * @param submittedOnDate
 * @param transactionRelations
 * @param type
 * @param unrecognizedIncomePortion
 */

@Serializable
data class GetLoansLoanIdTransactionsTransactionIdResponse(

    val amount: kotlin.Double? = null,

    val currency: GetLoansCurrency? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val externalId: kotlin.String? = null,

    val feeChargesPortion: kotlin.Double? = null,

    val id: kotlin.Long? = null,

    val interestPortion: kotlin.Double? = null,

    val loanChargePaidByList: kotlin.collections.Set<GetLoansLoanIdLoanChargePaidByData>? = null,

    val manuallyReversed: kotlin.Boolean? = null,

    val netDisbursalAmount: kotlin.Double? = null,

    val outstandingLoanBalance: kotlin.Double? = null,

    val overpaymentPortion: kotlin.Double? = null,

    val paymentDetailData: PaymentDetailData? = null,

    val penaltyChargesPortion: kotlin.Double? = null,

    @Contextual
    val possibleNextRepaymentDate: java.time.LocalDate? = null,

    val principalPortion: kotlin.Double? = null,

    val reversalExternalId: kotlin.String? = null,

    @Contextual
    val reversedOnDate: java.time.LocalDate? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null,

    val transactionRelations: kotlin.collections.Set<GetLoanTransactionRelation>? = null,

    val type: GetLoansType? = null,

    val unrecognizedIncomePortion: kotlin.Double? = null

)

