/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetLoanCollateralManagementTemplate
 *
 * @param basePrice
 * @param collateralId
 * @param name
 * @param pctToBase
 * @param quantity
 */

@Serializable
data class GetLoanCollateralManagementTemplate(

    @Contextual
    val basePrice: java.math.BigDecimal? = null,

    val collateralId: kotlin.Long? = null,

    val name: kotlin.String? = null,

    @Contextual
    val pctToBase: java.math.BigDecimal? = null,

    @Contextual
    val quantity: java.math.BigDecimal? = null

)

