/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetLoanAccountLockResponse
 *
 * @param content
 * @param limit
 * @param page
 */

@Serializable
data class GetLoanAccountLockResponse(

    val content: kotlin.collections.List<LoanAccountLock>? = null,

    val limit: kotlin.Int? = null,

    val page: kotlin.Int? = null

)

