/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetLoanRescheduleRequestResponse
 *
 * @param clientId
 * @param clientName
 * @param id
 * @param loanAccountNumber
 * @param loanId
 * @param loanTermVariationsData
 * @param recalculateInterest
 * @param rescheduleFromDate
 * @param rescheduleFromInstallment
 * @param rescheduleReasonCodeValue
 * @param rescheduleReasonComment
 * @param statusEnum
 * @param timeline
 */

@Serializable
data class GetLoanRescheduleRequestResponse(

    val clientId: kotlin.Long? = null,

    val clientName: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val loanAccountNumber: kotlin.String? = null,

    val loanId: kotlin.Long? = null,

    val loanTermVariationsData: kotlin.collections.Set<LoanTermVariationsData>? = null,

    val recalculateInterest: kotlin.Boolean? = null,

    @Contextual
    val rescheduleFromDate: java.time.LocalDate? = null,

    val rescheduleFromInstallment: kotlin.Int? = null,

    val rescheduleReasonCodeValue: RescheduleReasonsCodeValue? = null,

    val rescheduleReasonComment: kotlin.String? = null,

    val statusEnum: GetLoanRescheduleRequestStatus? = null,

    val timeline: RescheduleReasonsTimeline? = null

)

