/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param actualDisbursementDate
 * @param approvedPrincipal
 * @param chargeAmount
 * @param dateFormat
 * @param expectedDisbursementDate
 * @param id
 * @param loanChargeId
 * @param locale
 * @param netDisbursalAmount
 * @param note
 * @param principal
 * @param waivedChargeAmount
 */

@Serializable
data class GetLoansLoanIdDisbursementDetails(

    @Contextual
    val actualDisbursementDate: java.time.LocalDate? = null,

    val approvedPrincipal: kotlin.Float? = null,

    val chargeAmount: kotlin.Double? = null,

    val dateFormat: kotlin.String? = null,

    @Contextual
    val expectedDisbursementDate: java.time.LocalDate? = null,

    val id: kotlin.Int? = null,

    val loanChargeId: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val netDisbursalAmount: kotlin.Double? = null,

    val note: kotlin.String? = null,

    val principal: kotlin.Double? = null,

    val waivedChargeAmount: kotlin.Double? = null

)

