/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetLoansLoanIdTransactionsTemplateResponse
 *
 * @param date
 * @param total
 * @param transactionType
 */

@Serializable
data class GetLoansLoanIdTransactionsTemplateResponse(

    @Contextual
    val date: java.time.LocalDate? = null,

    val total: GetLoansTotal? = null,

    val transactionType: GetLoansTransactionType? = null

)

