/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetMakerCheckersSearchTemplateResponse
 *
 * @param actionNames
 * @param appUsers
 * @param entityNames
 * @param processingResults
 */

@Serializable
data class GetMakerCheckersSearchTemplateResponse(

    val actionNames: kotlin.collections.List<kotlin.String>? = null,

    val appUsers: kotlin.collections.List<AppUserData>? = null,

    val entityNames: kotlin.collections.List<kotlin.String>? = null,

    val processingResults: kotlin.collections.List<ProcessingResultLookup>? = null

)

