/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param action
 * @param actorId
 * @param content
 * @param createdAt
 * @param id
 * @param isRead
 * @param isSystemGenerated
 * @param objectId
 * @param objectType
 * @param officeId
 * @param tenantIdentifier
 * @param userIds
 */

@Serializable
data class GetNotification(

    val action: kotlin.String? = null,

    val actorId: kotlin.Long? = null,

    val content: kotlin.String? = null,

    val createdAt: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val isRead: kotlin.Boolean? = null,

    val isSystemGenerated: kotlin.Boolean? = null,

    val objectId: kotlin.Long? = null,

    val objectType: kotlin.String? = null,

    val officeId: kotlin.Long? = null,

    val tenantIdentifier: kotlin.String? = null,

    val userIds: kotlin.collections.List<kotlin.Long>? = null

)

