/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetOldestCOBProcessedLoanResponse
 *
 * @param cobBusinessDate
 * @param cobProcessedDate
 * @param loanIds
 */

@Serializable
data class GetOldestCOBProcessedLoanResponse(

    @Contextual
    val cobBusinessDate: java.time.LocalDate? = null,

    @Contextual
    val cobProcessedDate: java.time.LocalDate? = null,

    val loanIds: kotlin.collections.List<kotlin.Long>? = null

)

