/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNumber
 * @param amountReleased
 * @param amountTransferred
 * @param displayName
 * @param firstName
 * @param guaranteeAmount
 * @param lastName
 * @param loanAmount
 */

@Serializable
data class GetObligeeData(

    val accountNumber: kotlin.String? = null,

    val amountReleased: kotlin.Double? = null,

    val amountTransferred: kotlin.Double? = null,

    val displayName: kotlin.String? = null,

    val firstName: kotlin.String? = null,

    val guaranteeAmount: kotlin.Double? = null,

    val lastName: kotlin.String? = null,

    val loanAmount: kotlin.Double? = null

)

