/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetPostDatedChecks
 *
 * @param accountNo
 * @param amount
 * @param date
 * @param id
 * @param installmentId
 * @param name
 */

@Serializable
data class GetPostDatedChecks(

    val accountNo: kotlin.Long? = null,

    @Contextual
    val amount: java.math.BigDecimal? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val id: kotlin.Long? = null,

    val installmentId: kotlin.Int? = null,

    val name: kotlin.String? = null

)

