/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param incomeFromFeeAccountId
 * @param shareEquityId
 * @param shareReferenceId
 * @param shareSuspenseId
 */

@Serializable
data class GetProductsAccountingMappings(

    val incomeFromFeeAccountId: GetIncomeFromFeeAccountId? = null,

    val shareEquityId: GetShareEquityId? = null,

    val shareReferenceId: GetShareReferenceId? = null,

    val shareSuspenseId: GetShareSuspenseId? = null

)

