/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * GetProvisioningCriteriaResponse
 *
 * @param createdBy
 * @param criteriaId
 * @param criteriaName
 */

@Serializable
data class GetProvisioningCriteriaResponse(

    val createdBy: kotlin.String? = null,

    val criteriaId: kotlin.Long? = null,

    val criteriaName: kotlin.String? = null

)

