/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param fromDate
 * @param id
 * @param shareValue
 */

@Serializable
data class GetProductsMarketPrice(

    val fromDate: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val shareValue: kotlin.Int? = null

)

