/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountId
 * @param accountNumber
 * @param accountType
 * @param id
 * @param pocketId
 */

@Serializable
data class GetPocketLoanAccounts(

    val accountId: kotlin.Long? = null,

    val accountNumber: kotlin.Int? = null,

    val accountType: kotlin.Int? = null,

    val id: kotlin.Long? = null,

    val pocketId: kotlin.Long? = null

)

