/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * GetPasswordPreferencesTemplateResponse
 *
 * @param active
 * @param description
 * @param id
 * @param key
 */

@Serializable
data class GetPasswordPreferencesTemplateResponse(

    val active: kotlin.Boolean? = null,

    val description: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val key: kotlin.String? = null

)

