/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetReportMailingJobsTemplate
 *
 * @param emailAttachmentFileFormatOptions
 * @param isActive
 * @param stretchyReportParamDateOptions
 */

@Serializable
data class GetReportMailingJobsTemplate(

    val emailAttachmentFileFormatOptions: kotlin.collections.List<EnumOptionData>? = null,

    val isActive: kotlin.Boolean? = null,

    val stretchyReportParamDateOptions: kotlin.collections.List<EnumOptionData>? = null

)

