/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetRescheduleReasonsTemplateResponse
 *
 * @param rescheduleReasons
 */

@Serializable
data class GetRescheduleReasonsTemplateResponse(

    val rescheduleReasons: kotlin.collections.Set<GetRescheduleReasonsAllowedTypes>? = null

)

