/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetRolesRoleIdPermissionsResponse
 *
 * @param description
 * @param id
 * @param name
 * @param permissionUsageData
 */

@Serializable
data class GetRolesRoleIdPermissionsResponse(

    val description: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val permissionUsageData: kotlin.collections.List<GetRolesRoleIdPermissionsResponsePermissionData>? = null

)

