/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetReportMailingJobsResponse
 *
 * @param description
 * @param emailAttachmentFileFormat
 * @param emailMessage
 * @param emailRecipients
 * @param emailSubject
 * @param id
 * @param isActive
 * @param name
 * @param nextRunDateTime
 * @param numberOfRuns
 * @param recurrence
 * @param runAsUserId
 * @param startDateTime
 * @param stretchyReport
 * @param stretchyReportParamMap
 * @param timeline
 */

@Serializable
data class GetReportMailingJobsResponse(

    val description: kotlin.String? = null,

    val emailAttachmentFileFormat: EnumOptionData? = null,

    val emailMessage: kotlin.String? = null,

    val emailRecipients: kotlin.String? = null,

    val emailSubject: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val isActive: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    @Contextual
    val nextRunDateTime: java.time.OffsetDateTime? = null,

    val numberOfRuns: kotlin.Int? = null,

    val recurrence: kotlin.String? = null,

    val runAsUserId: kotlin.Long? = null,

    @Contextual
    val startDateTime: java.time.OffsetDateTime? = null,

    @Contextual
    val stretchyReport: kotlin.Any? = null,

    val stretchyReportParamMap: kotlin.String? = null,

    val timeline: ReportMailingJobTimelineData? = null

)

