/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse
 *
 * @param accountId
 * @param accountNo
 * @param amount
 * @param currency
 * @param date
 * @param id
 * @param paymentDetailData
 * @param reversed
 * @param runningBalance
 * @param transactionType
 */

@Serializable
data class GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse(

    val accountId: kotlin.Long? = null,

    val accountNo: kotlin.String? = null,

    val amount: kotlin.Float? = null,

    val currency: GetRecurringTransactionsCurrency? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val id: kotlin.Long? = null,

    val paymentDetailData: GetRecurringPaymentDetailData? = null,

    val reversed: kotlin.Boolean? = null,

    val runningBalance: kotlin.Int? = null,

    val transactionType: GetRecurringTransactionsTransactionType? = null

)

