/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetRecurringDepositAccountsTemplateResponse
 *
 * @param clientId
 * @param clientName
 * @param productOptions
 */

@Serializable
data class GetRecurringDepositAccountsTemplateResponse(

    val clientId: kotlin.Long? = null,

    val clientName: kotlin.String? = null,

    val productOptions: kotlin.collections.Set<GetRecurringProductOptions>? = null

)

