/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param actionName
 * @param code
 * @param entityName
 * @param grouping
 * @param selected
 */

@Serializable
data class GetRolesRoleIdPermissionsResponsePermissionData(

    val actionName: kotlin.String? = null,

    val code: kotlin.String? = null,

    val entityName: kotlin.String? = null,

    val grouping: kotlin.String? = null,

    val selected: kotlin.Boolean? = null

)

