/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetSelfLoansLoanIdTransactionsTransactionIdResponse
 *
 * @param amount
 * @param currency
 * @param date
 * @param id
 * @param interestPortion
 * @param manuallyReversed
 * @param type
 */

@Serializable
data class GetSelfLoansLoanIdTransactionsTransactionIdResponse(

    val amount: kotlin.Float? = null,

    val currency: GetLoanCurrency? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val id: kotlin.Int? = null,

    val interestPortion: kotlin.Float? = null,

    val manuallyReversed: kotlin.Boolean? = null,

    val type: GetSelfLoansLoanIdTransactionsType? = null

)

