/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNo
 * @param clientId
 * @param clientName
 * @param currency
 * @param fieldOfficerId
 * @param id
 * @param interestCalculationDaysInYearType
 * @param interestCalculationType
 * @param interestCompoundingPeriodType
 * @param interestPostingPeriodType
 * @param nominalAnnualInterestRate
 * @param savingsProductId
 * @param savingsProductName
 * @param status
 * @param summary
 * @param timeline
 */

@Serializable
data class GetSavingsPageItems(

    val accountNo: kotlin.String? = null,

    val clientId: kotlin.Int? = null,

    val clientName: kotlin.String? = null,

    val currency: GetSavingsCurrency? = null,

    val fieldOfficerId: kotlin.Int? = null,

    val id: kotlin.Int? = null,

    val interestCalculationDaysInYearType: GetSavingsInterestCalculationDaysInYearType? = null,

    val interestCalculationType: GetSavingsInterestCalculationType? = null,

    val interestCompoundingPeriodType: GetSavingsInterestCompoundingPeriodType? = null,

    val interestPostingPeriodType: GetSavingsInterestPostingPeriodType? = null,

    val nominalAnnualInterestRate: kotlin.Double? = null,

    val savingsProductId: kotlin.Int? = null,

    val savingsProductName: kotlin.String? = null,

    val status: GetSavingsStatus? = null,

    val summary: GetSavingsSummary? = null,

    val timeline: GetSavingsTimeline? = null

)

