/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountBalance
 * @param availableBalance
 * @param currency
 */

@Serializable
data class GetSavingsAccountsSummary(

    @Contextual
    val accountBalance: java.math.BigDecimal? = null,

    @Contextual
    val availableBalance: java.math.BigDecimal? = null,

    val currency: GetSavingsCurrency? = null

)

