/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param activatedByFirstname
 * @param activatedByLastname
 * @param activatedByUsername
 * @param activatedOnDate
 * @param submittedByFirstname
 * @param submittedByLastname
 * @param submittedByUsername
 * @param submittedOnDate
 */

@Serializable
data class GetSelfClientsTimeline(

    val activatedByFirstname: kotlin.String? = null,

    val activatedByLastname: kotlin.String? = null,

    val activatedByUsername: kotlin.String? = null,

    @Contextual
    val activatedOnDate: java.time.LocalDate? = null,

    val submittedByFirstname: kotlin.String? = null,

    val submittedByLastname: kotlin.String? = null,

    val submittedByUsername: kotlin.String? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null

)

