/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse
 *
 * @param accountId
 * @param accountNo
 * @param amount
 * @param currency
 * @param date
 * @param id
 * @param paymentDetailData
 * @param reversed
 * @param runningBalance
 * @param transactionType
 */

@Serializable
data class GetSelfSavingsAccountsAccountIdTransactionsTransactionIdResponse(

    val accountId: kotlin.Int? = null,

    val accountNo: kotlin.Long? = null,

    val amount: kotlin.Int? = null,

    val currency: GetSelfSavingsTransactionCurrency? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val id: kotlin.Int? = null,

    val paymentDetailData: GetSelfSavingsPaymentDetailData? = null,

    val reversed: kotlin.Boolean? = null,

    val runningBalance: kotlin.Int? = null,

    val transactionType: GetSelfSavingsTransactionType? = null

)

