/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param disabled
 * @param glCode
 * @param id
 * @param manualEntriesAllowed
 * @param name
 * @param nameDecorated
 * @param tagId
 * @param type
 * @param usage
 */

@Serializable
data class GetSavingsProductsLiabilityAccountOptions(

    val disabled: kotlin.Boolean? = null,

    val glCode: kotlin.String? = null,

    val id: kotlin.Int? = null,

    val manualEntriesAllowed: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val nameDecorated: kotlin.String? = null,

    val tagId: GetSavingsProductsLiabilityTagId? = null,

    val type: GetSavingsProductsLiabilityType? = null,

    val usage: GetSavingsProductsLiabilityUsage? = null

)

