/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNo
 * @param activationDate
 * @param active
 * @param displayName
 * @param fullname
 * @param id
 * @param officeId
 * @param officeName
 * @param status
 */

@Serializable
data class GetSelfClientsPageItems(

    val accountNo: kotlin.Long? = null,

    @Contextual
    val activationDate: java.time.LocalDate? = null,

    val active: kotlin.Boolean? = null,

    val displayName: kotlin.String? = null,

    val fullname: kotlin.String? = null,

    val id: kotlin.Int? = null,

    val officeId: kotlin.Int? = null,

    val officeName: kotlin.String? = null,

    val status: GetSelfClientsStatus? = null

)

