/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param amount
 * @param calculationType
 * @param chargeAppliesTo
 * @param chargeTimeType
 * @param currency
 * @param id
 * @param name
 * @param paymentMode
 * @param penalty
 */

@Serializable
data class GetShareAccountsChargeOptions(

    val active: kotlin.Boolean? = null,

    val amount: kotlin.Int? = null,

    val calculationType: GetShareAccountsChargeCalculationType? = null,

    val chargeAppliesTo: GetShareAccountsChargeAppliesTo? = null,

    val chargeTimeType: GetShareAccountsChargeTimeType? = null,

    val currency: GetShareAccountsCurrency? = null,

    val id: kotlin.Int? = null,

    val name: kotlin.String? = null,

    val paymentMode: GetShareAccountsChargePaymentMode? = null,

    val penalty: kotlin.Boolean? = null

)

