/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetSelfLoansTemplateResponse
 *
 * @param clientId
 * @param clientName
 * @param clientOfficeId
 * @param productOptions
 * @param timeline
 */

@Serializable
data class GetSelfLoansTemplateResponse(

    val clientId: kotlin.Int? = null,

    val clientName: kotlin.String? = null,

    val clientOfficeId: kotlin.Int? = null,

    val productOptions: kotlin.collections.Set<GetSelfLoansProductOptions>? = null,

    val timeline: GetSelfLoansTimeline? = null

)

