/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param incomeFromFeeAccount
 * @param incomeFromPenaltyAccount
 * @param interestOnSavingsAccount
 * @param savingsControlAccount
 * @param savingsReferenceAccount
 * @param transfersInSuspenseAccount
 */

@Serializable
data class GetSavingsProductsAccountingMappings(

    val incomeFromFeeAccount: GetSavingsProductsIncomeFromFeeAccount? = null,

    val incomeFromPenaltyAccount: GetSavingsProductsIncomeFromPenaltyAccount? = null,

    val interestOnSavingsAccount: GetSavingsProductsInterestOnSavingsAccount? = null,

    val savingsControlAccount: GetSavingsProductsSavingsControlAccount? = null,

    val savingsReferenceAccount: GetSavingsProductsSavingsReferenceAccount? = null,

    val transfersInSuspenseAccount: GetSavingsProductsTransfersInSuspenseAccount? = null

)

