/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetSelfBeneficiariesTPTResponse
 *
 * @param accountNumber
 * @param accountType
 * @param clientName
 * @param id
 * @param name
 * @param officeName
 * @param transferLimit
 */

@Serializable
data class GetSelfBeneficiariesTPTResponse(

    val accountNumber: kotlin.Long? = null,

    val accountType: GetSelfBeneficiariesAccountOptions? = null,

    val clientName: kotlin.String? = null,

    val id: kotlin.Int? = null,

    val name: kotlin.String? = null,

    val officeName: kotlin.String? = null,

    val transferLimit: kotlin.Int? = null

)

