/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetSurveyResponse
 *
 * @param datatableData
 * @param enabled
 */

@Serializable
data class GetSurveyResponse(

    val datatableData: GetSurveyResponseDatatableData? = null,

    val enabled: kotlin.Boolean? = null

)

