/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountId
 * @param accountNo
 * @param amount
 * @param chargesPaidByData
 * @param currency
 * @param date
 * @param entryType
 * @param id
 * @param interestedPostedAsOn
 * @param isManualTransaction
 * @param isReversal
 * @param lienTransaction
 * @param originalTransactionId
 * @param paymentDetailData
 * @param releaseTransactionId
 * @param reversed
 * @param runningBalance
 * @param submittedByUsername
 * @param submittedOnDate
 * @param transactionType
 */

@Serializable
data class GetSavingsAccountTransactionsPageItem(

    val accountId: kotlin.Long? = null,

    val accountNo: kotlin.String? = null,

    @Contextual
    val amount: java.math.BigDecimal? = null,

    val chargesPaidByData: kotlin.collections.Set<GetSavingsAccountChargesPaidByData>? = null,

    val currency: GetTransactionsCurrency? = null,

    @Contextual
    val date: java.time.LocalDate? = null,

    val entryType: GetSavingsAccountTransactionsPageItem.EntryType? = null,

    val id: kotlin.Long? = null,

    val interestedPostedAsOn: kotlin.Boolean? = null,

    val isManualTransaction: kotlin.Boolean? = null,

    val isReversal: kotlin.Boolean? = null,

    val lienTransaction: kotlin.Boolean? = null,

    val originalTransactionId: kotlin.Long? = null,

    val paymentDetailData: GetTransactionsPaymentDetailData? = null,

    val releaseTransactionId: kotlin.Long? = null,

    val reversed: kotlin.Boolean? = null,

    @Contextual
    val runningBalance: java.math.BigDecimal? = null,

    val submittedByUsername: kotlin.String? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null,

    val transactionType: GetTranscationEnumData? = null

) {

    /**
     *
     *
     * Values: CREDIT,DEBIT
     */
    @JsonClass(generateAdapter = false)
    enum class EntryType(val value: kotlin.String) {
        @Json(name = "CREDIT")
        CREDIT("CREDIT"),
        @Json(name = "DEBIT")
        DEBIT("DEBIT");
    }

}

