/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param amount
 * @param chargeCalculationType
 * @param chargeTimeType
 * @param chargesAppliesTo
 * @param currency
 * @param id
 * @param name
 * @param penalty
 */

@Serializable
data class GetSavingsChargesOptions(

    val active: kotlin.Boolean? = null,

    val amount: kotlin.Float? = null,

    val chargeCalculationType: GetChargesChargeCalculationType? = null,

    val chargeTimeType: GetSavingsChargesChargeTimeType? = null,

    val chargesAppliesTo: GetChargesAppliesTo? = null,

    val currency: GetChargesCurrencyResponse? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val penalty: kotlin.Boolean? = null

)

