/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetSavingsProductsResponse
 *
 * @param accountingRule
 * @param currency
 * @param description
 * @param id
 * @param interestCalculationDaysInYearType
 * @param interestCalculationType
 * @param interestCompoundingPeriodType
 * @param interestPostingPeriodType
 * @param name
 * @param nominalAnnualInterestRate
 * @param shortName
 * @param withdrawalFeeForTransfers
 */

@Serializable
data class GetSavingsProductsResponse(

    val accountingRule: GetSavingsProductsAccountingRule? = null,

    val currency: GetSavingsCurrency? = null,

    val description: kotlin.String? = null,

    val id: kotlin.Int? = null,

    val interestCalculationDaysInYearType: GetSavingsProductsInterestCalculationDaysInYearType? = null,

    val interestCalculationType: GetSavingsProductsInterestCalculationType? = null,

    val interestCompoundingPeriodType: GetSavingsProductsInterestCompoundingPeriodType? = null,

    val interestPostingPeriodType: GetSavingsProductsInterestPostingPeriodType? = null,

    val name: kotlin.String? = null,

    @Contextual
    val nominalAnnualInterestRate: java.math.BigDecimal? = null,

    val shortName: kotlin.String? = null,

    val withdrawalFeeForTransfers: kotlin.Boolean? = null

)

