/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNo
 * @param externalId
 * @param id
 * @param loanCycle
 * @param loanType
 * @param productId
 * @param productName
 * @param status
 */

@Serializable
data class GetSelfClientsLoanAccounts(

    val accountNo: kotlin.Long? = null,

    val externalId: kotlin.Int? = null,

    val id: kotlin.Int? = null,

    val loanCycle: kotlin.Int? = null,

    val loanType: GetSelfClientsLoanAccountsType? = null,

    val productId: kotlin.Int? = null,

    val productName: kotlin.String? = null,

    val status: GetSelfClientsLoanAccountsStatus? = null

)

