/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param code
 * @param description
 * @param id
 */

@Serializable
data class GetSelfClientsStatus(

    val code: kotlin.String? = null,

    val description: kotlin.String? = null,

    val id: kotlin.Int? = null

)

