/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetTaxesGroupResponse
 *
 * @param id
 * @param name
 * @param taxAssociations
 */

@Serializable
data class GetTaxesGroupResponse(

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val taxAssociations: kotlin.collections.Set<GetTaxesGroupTaxAssociations>? = null

)

