/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetTellersTellerIdCashiersResponse
 *
 * @param cashiers
 * @param officeId
 * @param officeName
 * @param tellerId
 * @param tellerName
 */

@Serializable
data class GetTellersTellerIdCashiersResponse(

    val cashiers: kotlin.collections.List<CashierData>? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    val tellerId: kotlin.Long? = null,

    val tellerName: kotlin.String? = null

)

