/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetTellersTellerIdCashiersCashiersIdSummaryAndTransactionsResponse
 *
 * @param cashierId
 * @param cashierName
 * @param cashierTransactions
 * @param netCash
 * @param officeName
 * @param sumCashAllocation
 * @param sumCashSettlement
 * @param sumInwardCash
 * @param sumOutwardCash
 * @param tellerId
 * @param tellerName
 */

@Serializable
data class GetTellersTellerIdCashiersCashiersIdSummaryAndTransactionsResponse(

    val cashierId: kotlin.Long? = null,

    val cashierName: kotlin.String? = null,

    val cashierTransactions: PageCashierTransactionData? = null,

    @Contextual
    val netCash: java.math.BigDecimal? = null,

    val officeName: kotlin.String? = null,

    @Contextual
    val sumCashAllocation: java.math.BigDecimal? = null,

    @Contextual
    val sumCashSettlement: java.math.BigDecimal? = null,

    @Contextual
    val sumInwardCash: java.math.BigDecimal? = null,

    @Contextual
    val sumOutwardCash: java.math.BigDecimal? = null,

    val tellerId: kotlin.Long? = null,

    val tellerName: kotlin.String? = null

)

