/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetTellersTellerIdCashiersCashiersIdTransactionsResponse
 *
 * @param cashierId
 * @param cashierName
 * @param createdDate
 * @param entityId
 * @param entityType
 * @param id
 * @param officeId
 * @param officeName
 * @param tellerId
 * @param txnAmount
 * @param txnDate
 * @param txnNote
 * @param txnType
 */

@Serializable
data class GetTellersTellerIdCashiersCashiersIdTransactionsResponse(

    val cashierId: kotlin.Long? = null,

    val cashierName: kotlin.String? = null,

    @Contextual
    val createdDate: java.time.OffsetDateTime? = null,

    val entityId: kotlin.Long? = null,

    val entityType: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    val tellerId: kotlin.Long? = null,

    @Contextual
    val txnAmount: java.math.BigDecimal? = null,

    @Contextual
    val txnDate: java.time.LocalDate? = null,

    val txnNote: kotlin.String? = null,

    val txnType: CashierTxnType? = null

)

