/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * GetTellersTellerIdCashiersCashierIdResponse
 *
 * @param description
 * @param endDate
 * @param endTime
 * @param id
 * @param isFullDay
 * @param staffId
 * @param staffName
 * @param startDate
 * @param startTime
 * @param tellerId
 * @param tellerName
 */

@Serializable
data class GetTellersTellerIdCashiersCashierIdResponse(

    val description: kotlin.String? = null,

    @Contextual
    val endDate: java.time.LocalDate? = null,

    val endTime: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val isFullDay: kotlin.Boolean? = null,

    val staffId: kotlin.Long? = null,

    val staffName: kotlin.String? = null,

    @Contextual
    val startDate: java.time.LocalDate? = null,

    val startTime: kotlin.String? = null,

    val tellerId: kotlin.Long? = null,

    val tellerName: kotlin.String? = null

)

