/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param startDate
 * @param taxComponent
 */

@Serializable
data class GetTaxesGroupTaxAssociations(

    val id: kotlin.Long? = null,

    @Contextual
    val startDate: java.time.LocalDate? = null,

    val taxComponent: GetTaxesGroupTaxComponent? = null

)

