/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * GetUsersTemplateResponse
 *
 * @param allowedOffices
 * @param availableRoles
 * @param selfServiceRoles
 */

@Serializable
data class GetUsersTemplateResponse(

    val allowedOffices: kotlin.collections.List<OfficeData>? = null,

    val availableRoles: kotlin.collections.List<RoleData>? = null,

    val selfServiceRoles: kotlin.collections.List<RoleData>? = null

)

