/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dateValue
 * @param description
 * @param enabled
 * @param id
 * @param name
 * @param stringValue
 * @param trapDoor
 * @param `value`
 */

@Serializable
data class GlobalConfigurationPropertyData(

    @Contextual
    val dateValue: java.time.LocalDate? = null,

    val description: kotlin.String? = null,

    val enabled: kotlin.Boolean? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val stringValue: kotlin.String? = null,

    val trapDoor: kotlin.Boolean? = null,

    val value: kotlin.Long? = null

)

