/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param center
 * @param group
 * @param id
 * @param levelName
 * @param new
 * @param parentId
 * @param recursable
 * @param superParent
 */

@Serializable
data class GroupLevel(

    val center: kotlin.Boolean? = null,

    val group: kotlin.Boolean? = null,

    val id: kotlin.Long? = null,

    val levelName: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    val parentId: kotlin.Long? = null,

    val recursable: kotlin.Boolean? = null,

    val superParent: kotlin.Boolean? = null

)

