/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Client
import org.openapitools.client.models.GroupLevel
import org.openapitools.client.models.Office
import org.openapitools.client.models.Staff

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param accountNumberRequiresAutoGeneration 
 * @param activationDate 
 * @param active 
 * @param activeClientMembers 
 * @param center 
 * @param childGroup 
 * @param clientMembers 
 * @param closed 
 * @param group 
 * @param groupLevel 
 * @param groupMembers 
 * @param id 
 * @param new 
 * @param notActive 
 * @param notPending 
 * @param office 
 * @param parent 
 * @param pending 
 * @param staff 
 * @param submittedOnDate 
 * @param transferInProgress 
 * @param transferInProgressOrOnHold 
 * @param transferOnHold 
 */

@Serializable
data class Group (

    val accountNumberRequiresAutoGeneration: kotlin.Boolean? = null,

    @Contextual
    val activationDate: java.time.LocalDate? = null,

    val active: kotlin.Boolean? = null,

    val activeClientMembers: kotlin.collections.Set<Client>? = null,

    val center: kotlin.Boolean? = null,

    val childGroup: kotlin.Boolean? = null,

    val clientMembers: kotlin.collections.Set<Client>? = null,

    val closed: kotlin.Boolean? = null,

    val group: kotlin.Boolean? = null,

    val groupLevel: GroupLevel? = null,

    val groupMembers: kotlin.collections.List<Group>? = null,

    val id: kotlin.Long? = null,

    val new: kotlin.Boolean? = null,

    val notActive: kotlin.Boolean? = null,

    val notPending: kotlin.Boolean? = null,

    val office: Office? = null,

    val parent: Group? = null,

    val pending: kotlin.Boolean? = null,

    val staff: Staff? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null,

    val transferInProgress: kotlin.Boolean? = null,

    val transferInProgressOrOnHold: kotlin.Boolean? = null,

    val transferOnHold: kotlin.Boolean? = null

) {


}

