/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param location
 * @param new
 * @param storageType
 */

@Serializable
data class Image(

    val id: kotlin.Long? = null,

    val location: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    val storageType: kotlin.Int? = null

)

