/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * InlineJobRequest
 *
 * @param loanIds
 */

@Serializable
data class InlineJobRequest(

    val loanIds: kotlin.collections.List<kotlin.Long>? = null

)

