/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param quoteCode
 * @param state
 * @param transactionCode
 * @param changes
 * @param clientId
 * @param commandId
 * @param creditBureauReportData
 * @param expiration
 * @param extensionList
 * @param fspCommission
 * @param fspFee
 * @param glimId
 * @param groupId
 * @param gsimId
 * @param loanId
 * @param officeId
 * @param productId
 * @param resourceExternalId
 * @param resourceId
 * @param resourceIdentifier
 * @param rollbackTransaction
 * @param savingsId
 * @param subResourceExternalId
 * @param subResourceId
 * @param transactionId
 */

@Serializable
data class InteropQuoteResponseData(

    val quoteCode: kotlin.String,

    val state: InteropQuoteResponseData.State,

    val transactionCode: kotlin.String,

    val changes: kotlin.collections.Map<kotlin.String, @Contextual kotlin.Any>? = null,

    val clientId: kotlin.Long? = null,

    val commandId: kotlin.Long? = null,

    val creditBureauReportData: kotlin.collections.Map<kotlin.String, @Contextual kotlin.Any>? = null,

    val expiration: kotlin.String? = null,

    val extensionList: kotlin.collections.List<ExtensionData>? = null,

    val fspCommission: MoneyData? = null,

    val fspFee: MoneyData? = null,

    val glimId: kotlin.Long? = null,

    val groupId: kotlin.Long? = null,

    val gsimId: kotlin.Long? = null,

    val loanId: kotlin.Long? = null,

    val officeId: kotlin.Long? = null,

    val productId: kotlin.Long? = null,

    val resourceExternalId: ExternalId? = null,

    val resourceId: kotlin.Long? = null,

    val resourceIdentifier: kotlin.String? = null,

    val rollbackTransaction: kotlin.Boolean? = null,

    val savingsId: kotlin.Long? = null,

    val subResourceExternalId: ExternalId? = null,

    val subResourceId: kotlin.Long? = null,

    val transactionId: kotlin.String? = null

) {

    /**
     *
     *
     * Values: ACCEPTED,REJECTED
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "ACCEPTED")
        ACCEPTED("ACCEPTED"),

        @Json(name = "REJECTED")
        REJECTED("REJECTED");
    }

}

