/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountId
 * @param amount
 * @param transactionCode
 * @param transactionRole
 * @param transferCode
 * @param expiration
 * @param expirationLocalDate
 * @param extensionList
 * @param fspCommission
 * @param fspFee
 * @param geoCode
 * @param note
 * @param requestCode
 * @param transactionType
 */

@Serializable
data class InteropTransferRequestData(

    val accountId: kotlin.String,

    val amount: MoneyData,

    val transactionCode: kotlin.String,

    val transactionRole: InteropTransferRequestData.TransactionRole,

    val transferCode: kotlin.String,

    @Contextual
    val expiration: java.time.OffsetDateTime? = null,

    @Contextual
    val expirationLocalDate: java.time.LocalDate? = null,

    val extensionList: kotlin.collections.List<ExtensionData>? = null,

    val fspCommission: MoneyData? = null,

    val fspFee: MoneyData? = null,

    val geoCode: GeoCodeData? = null,

    val note: kotlin.String? = null,

    val requestCode: kotlin.String? = null,

    val transactionType: InteropTransactionTypeData? = null

) {

    /**
     *
     *
     * Values: PAYER,PAYEE
     */
    @JsonClass(generateAdapter = false)
    enum class TransactionRole(val value: kotlin.String) {
        @Json(name = "PAYER")
        PAYER("PAYER"),

        @Json(name = "PAYEE")
        PAYEE("PAYEE");
    }

}

