/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * IsCatchUpRunningResponse
 *
 * @param isCatchUpRunning
 * @param processingDate
 */

@Serializable
data class IsCatchUpRunningResponse(

    val isCatchUpRunning: kotlin.Boolean? = null,

    @Contextual
    val processingDate: java.time.LocalDate? = null

)

