/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param parameterName
 * @param parameterValue
 */

@Serializable
data class JobParameterDTO(

    val parameterName: kotlin.String? = null,

    val parameterValue: kotlin.String? = null

)

