/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param amount
 * @param comments
 * @param createdByUserId
 * @param createdByUserName
 * @param createdDate
 * @param currency
 * @param entityId
 * @param entityType
 * @param entryType
 * @param glAccountCode
 * @param glAccountId
 * @param glAccountName
 * @param glAccountType
 * @param id
 * @param manualEntry
 * @param officeId
 * @param officeName
 * @param officeRunningBalance
 * @param organizationRunningBalance
 * @param referenceNumber
 * @param reversed
 * @param runningBalanceComputed
 * @param submittedOnDate
 * @param transactionDate
 * @param transactionDetails
 * @param transactionId
 */

@Serializable
data class JournalEntryTransactionItem(

    val amount: kotlin.Double? = null,

    val comments: kotlin.String? = null,

    val createdByUserId: kotlin.Long? = null,

    val createdByUserName: kotlin.String? = null,

    @Contextual
    val createdDate: java.time.LocalDate? = null,

    val currency: CurrencyItem? = null,

    val entityId: kotlin.Long? = null,

    val entityType: EnumOptionType? = null,

    val entryType: EnumOptionType? = null,

    val glAccountCode: kotlin.String? = null,

    val glAccountId: kotlin.Long? = null,

    val glAccountName: kotlin.String? = null,

    val glAccountType: EnumOptionType? = null,

    val id: kotlin.Long? = null,

    val manualEntry: kotlin.Boolean? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    @Contextual
    val officeRunningBalance: java.math.BigDecimal? = null,

    @Contextual
    val organizationRunningBalance: java.math.BigDecimal? = null,

    val referenceNumber: kotlin.String? = null,

    val reversed: kotlin.Boolean? = null,

    val runningBalanceComputed: kotlin.Boolean? = null,

    @Contextual
    val submittedOnDate: java.time.LocalDate? = null,

    @Contextual
    val transactionDate: java.time.LocalDate? = null,

    val transactionDetails: TransactionDetails? = null,

    val transactionId: kotlin.String? = null

)

