/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param allowPartialPeriodInterestCalcualtion
 * @param amortizationMethod
 * @param annualNominalInterestRate
 * @param arrearsTolerance
 * @param currency
 * @param disableScheduleExtensionForDownPayment
 * @param disbursedAmountPercentageForDownPayment
 * @param enableAutoRepaymentForDownPayment
 * @param enableDownPayment
 * @param equalAmortization
 * @param graceOnArrearsAgeing
 * @param graceOnDueDate
 * @param graceOnInterestPayment
 * @param graceOnPrincipalPayment
 * @param inArrearsTolerance
 * @param interestCalculationPeriodMethod
 * @param interestMethod
 * @param interestPeriodFrequencyType
 * @param interestRecalculationEnabled
 * @param loanScheduleProcessingType
 * @param loanScheduleType
 * @param nominalInterestRatePerPeriod
 * @param numberOfRepayments
 * @param principal
 * @param repayEvery
 * @param repaymentPeriodFrequencyType
 */

@Serializable
data class LoanProductRelatedDetail(

    val allowPartialPeriodInterestCalcualtion: kotlin.Boolean? = null,

    val amortizationMethod: LoanProductRelatedDetail.AmortizationMethod? = null,

    @Contextual
    val annualNominalInterestRate: java.math.BigDecimal? = null,

    @Contextual
    val arrearsTolerance: java.math.BigDecimal? = null,

    val currency: MonetaryCurrency? = null,

    val disableScheduleExtensionForDownPayment: kotlin.Boolean? = null,

    @Contextual
    val disbursedAmountPercentageForDownPayment: java.math.BigDecimal? = null,

    val enableAutoRepaymentForDownPayment: kotlin.Boolean? = null,

    val enableDownPayment: kotlin.Boolean? = null,

    val equalAmortization: kotlin.Boolean? = null,

    val graceOnArrearsAgeing: kotlin.Int? = null,

    val graceOnDueDate: kotlin.Int? = null,

    val graceOnInterestPayment: kotlin.Int? = null,

    val graceOnPrincipalPayment: kotlin.Int? = null,

    val inArrearsTolerance: Money? = null,

    val interestCalculationPeriodMethod: LoanProductRelatedDetail.InterestCalculationPeriodMethod? = null,

    val interestMethod: LoanProductRelatedDetail.InterestMethod? = null,

    val interestPeriodFrequencyType: LoanProductRelatedDetail.InterestPeriodFrequencyType? = null,

    val interestRecalculationEnabled: kotlin.Boolean? = null,

    val loanScheduleProcessingType: LoanProductRelatedDetail.LoanScheduleProcessingType? = null,

    val loanScheduleType: LoanProductRelatedDetail.LoanScheduleType? = null,

    @Contextual
    val nominalInterestRatePerPeriod: java.math.BigDecimal? = null,

    val numberOfRepayments: kotlin.Int? = null,

    val principal: Money? = null,

    val repayEvery: kotlin.Int? = null,

    val repaymentPeriodFrequencyType: LoanProductRelatedDetail.RepaymentPeriodFrequencyType? = null

) {

    /**
     *
     *
     * Values: EQUAL_PRINCIPAL,EQUAL_INSTALLMENTS,INVALID
     */
    @JsonClass(generateAdapter = false)
    enum class AmortizationMethod(val value: kotlin.String) {
        @Json(name = "EQUAL_PRINCIPAL")
        EQUAL_PRINCIPAL("EQUAL_PRINCIPAL"),

        @Json(name = "EQUAL_INSTALLMENTS")
        EQUAL_INSTALLMENTS("EQUAL_INSTALLMENTS"),

        @Json(name = "INVALID")
        INVALID("INVALID");
    }

    /**
     *
     *
     * Values: DAILY,SAME_AS_REPAYMENT_PERIOD,INVALID
     */
    @JsonClass(generateAdapter = false)
    enum class InterestCalculationPeriodMethod(val value: kotlin.String) {
        @Json(name = "DAILY")
        DAILY("DAILY"),

        @Json(name = "SAME_AS_REPAYMENT_PERIOD")
        SAME_AS_REPAYMENT_PERIOD("SAME_AS_REPAYMENT_PERIOD"),

        @Json(name = "INVALID")
        INVALID("INVALID");
    }

    /**
     *
     *
     * Values: DECLINING_BALANCE,FLAT,INVALID
     */
    @JsonClass(generateAdapter = false)
    enum class InterestMethod(val value: kotlin.String) {
        @Json(name = "DECLINING_BALANCE")
        DECLINING_BALANCE("DECLINING_BALANCE"),

        @Json(name = "FLAT")
        FLAT("FLAT"),

        @Json(name = "INVALID")
        INVALID("INVALID");
    }

    /**
     *
     *
     * Values: DAYS,WEEKS,MONTHS,YEARS,WHOLE_TERM,INVALID
     */
    @JsonClass(generateAdapter = false)
    enum class InterestPeriodFrequencyType(val value: kotlin.String) {
        @Json(name = "DAYS")
        DAYS("DAYS"),

        @Json(name = "WEEKS")
        WEEKS("WEEKS"),

        @Json(name = "MONTHS")
        MONTHS("MONTHS"),

        @Json(name = "YEARS")
        YEARS("YEARS"),

        @Json(name = "WHOLE_TERM")
        WHOLE_TERM("WHOLE_TERM"),

        @Json(name = "INVALID")
        INVALID("INVALID");
    }

    /**
     *
     *
     * Values: HORIZONTAL,VERTICAL
     */
    @JsonClass(generateAdapter = false)
    enum class LoanScheduleProcessingType(val value: kotlin.String) {
        @Json(name = "HORIZONTAL")
        HORIZONTAL("HORIZONTAL"),

        @Json(name = "VERTICAL")
        VERTICAL("VERTICAL");
    }

    /**
     *
     *
     * Values: CUMULATIVE,PROGRESSIVE
     */
    @JsonClass(generateAdapter = false)
    enum class LoanScheduleType(val value: kotlin.String) {
        @Json(name = "CUMULATIVE")
        CUMULATIVE("CUMULATIVE"),

        @Json(name = "PROGRESSIVE")
        PROGRESSIVE("PROGRESSIVE");
    }

    /**
     *
     *
     * Values: DAYS,WEEKS,MONTHS,YEARS,WHOLE_TERM,INVALID
     */
    @JsonClass(generateAdapter = false)
    enum class RepaymentPeriodFrequencyType(val value: kotlin.String) {
        @Json(name = "DAYS")
        DAYS("DAYS"),

        @Json(name = "WEEKS")
        WEEKS("WEEKS"),

        @Json(name = "MONTHS")
        MONTHS("MONTHS"),

        @Json(name = "YEARS")
        YEARS("YEARS"),

        @Json(name = "WHOLE_TERM")
        WHOLE_TERM("WHOLE_TERM"),

        @Json(name = "INVALID")
        INVALID("INVALID");
    }

}

