/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param defaultDifferentialLendingRate
 * @param floatingInterestRateCalculationAllowed
 * @param floatingRate
 * @param id
 * @param interestRateDifferential
 * @param loanProduct
 * @param maxDifferentialLendingRate
 * @param minDifferentialLendingRate
 * @param new
 */

@Serializable
data class LoanProductFloatingRates(

    @Contextual
    val defaultDifferentialLendingRate: java.math.BigDecimal? = null,

    val floatingInterestRateCalculationAllowed: kotlin.Boolean? = null,

    val floatingRate: FloatingRate? = null,

    val id: kotlin.Long? = null,

    @Contextual
    val interestRateDifferential: java.math.BigDecimal? = null,

    val loanProduct: LoanProduct? = null,

    @Contextual
    val maxDifferentialLendingRate: java.math.BigDecimal? = null,

    @Contextual
    val minDifferentialLendingRate: java.math.BigDecimal? = null,

    val new: kotlin.Boolean? = null

)

