/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param amortizationBoolean
 * @param amortizationType
 * @param arrearsToleranceBoolean
 * @param graceOnArrearsAgeing
 * @param graceOnArrearsAgingBoolean
 * @param graceOnPrincipalAndInterestPayment
 * @param graceOnPrincipalAndInterestPaymentBoolean
 * @param id
 * @param inArrearsTolerance
 * @param interestCalcPeriodBoolean
 * @param interestCalculationPeriodType
 * @param interestMethodBoolean
 * @param interestType
 * @param loanProduct
 * @param new
 * @param repaymentEvery
 * @param repaymentEveryBoolean
 * @param transactionProcessingStrategyBoolean
 * @param transactionProcessingStrategyCode
 */

@Serializable
data class LoanProductConfigurableAttributes(

    val amortizationBoolean: kotlin.Boolean? = null,

    val amortizationType: kotlin.Boolean? = null,

    val arrearsToleranceBoolean: kotlin.Boolean? = null,

    val graceOnArrearsAgeing: kotlin.Boolean? = null,

    val graceOnArrearsAgingBoolean: kotlin.Boolean? = null,

    val graceOnPrincipalAndInterestPayment: kotlin.Boolean? = null,

    val graceOnPrincipalAndInterestPaymentBoolean: kotlin.Boolean? = null,

    val id: kotlin.Long? = null,

    val inArrearsTolerance: kotlin.Boolean? = null,

    val interestCalcPeriodBoolean: kotlin.Boolean? = null,

    val interestCalculationPeriodType: kotlin.Boolean? = null,

    val interestMethodBoolean: kotlin.Boolean? = null,

    val interestType: kotlin.Boolean? = null,

    val loanProduct: LoanProduct? = null,

    val new: kotlin.Boolean? = null,

    val repaymentEvery: kotlin.Boolean? = null,

    val repaymentEveryBoolean: kotlin.Boolean? = null,

    val transactionProcessingStrategyBoolean: kotlin.Boolean? = null,

    val transactionProcessingStrategyCode: kotlin.Boolean? = null

)

