/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dateValue
 * @param decimalValue
 * @param id
 * @param isProcessed
 * @param isSpecificToInstallment
 * @param termType
 * @param termVariationApplicableFrom
 */

@Serializable
data class LoanTermVariationsData(

    @Contextual
    val dateValue: java.time.LocalDate? = null,

    @Contextual
    val decimalValue: java.math.BigDecimal? = null,

    val id: kotlin.Long? = null,

    val isProcessed: kotlin.Boolean? = null,

    val isSpecificToInstallment: kotlin.Boolean? = null,

    val termType: LoanTermTypeOptions? = null,

    @Contextual
    val termVariationApplicableFrom: java.time.LocalDate? = null

)

