/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param error
 * @param loanId
 * @param lockOwner
 * @param lockPlacedOn
 * @param lockPlacedOnCobBusinessDate
 * @param newLockOwner
 * @param stacktrace
 * @param version
 */

@Serializable
data class LoanAccountLock(

    val error: kotlin.String? = null,

    val loanId: kotlin.Long? = null,

    val lockOwner: LoanAccountLock.LockOwner? = null,

    @Contextual
    val lockPlacedOn: java.time.OffsetDateTime? = null,

    @Contextual
    val lockPlacedOnCobBusinessDate: java.time.LocalDate? = null,

    val newLockOwner: LoanAccountLock.NewLockOwner? = null,

    val stacktrace: kotlin.String? = null,

    val version: kotlin.Long? = null

) {

    /**
     *
     *
     * Values: COB_CHUNK_PROCESSING,INLINE_COB_PROCESSING
     */
    @JsonClass(generateAdapter = false)
    enum class LockOwner(val value: kotlin.String) {
        @Json(name = "LOAN_COB_CHUNK_PROCESSING")
        COB_CHUNK_PROCESSING("LOAN_COB_CHUNK_PROCESSING"),

        @Json(name = "LOAN_INLINE_COB_PROCESSING")
        INLINE_COB_PROCESSING("LOAN_INLINE_COB_PROCESSING");
    }

    /**
     *
     *
     * Values: COB_CHUNK_PROCESSING,INLINE_COB_PROCESSING
     */
    @JsonClass(generateAdapter = false)
    enum class NewLockOwner(val value: kotlin.String) {
        @Json(name = "LOAN_COB_CHUNK_PROCESSING")
        COB_CHUNK_PROCESSING("LOAN_COB_CHUNK_PROCESSING"),

        @Json(name = "LOAN_INLINE_COB_PROCESSING")
        INLINE_COB_PROCESSING("LOAN_INLINE_COB_PROCESSING");
    }

}

