/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param amountreserved
 * @param balance
 * @param categoryId
 * @param categoryName
 * @param criteriaId
 * @param currencyCode
 * @param expenseAccount
 * @param expenseAccountCode
 * @param expenseAccountName
 * @param historyId
 * @param liabilityAccountCode
 * @param liabilityAccountName
 * @param liablityAccount
 * @param officeId
 * @param officeName
 * @param overdueInDays
 * @param percentage
 * @param productId
 * @param productName
 */

@Serializable
data class LoanProductProvisioningEntryData(

    @Contextual
    val amountreserved: java.math.BigDecimal? = null,

    @Contextual
    val balance: java.math.BigDecimal? = null,

    val categoryId: kotlin.Long? = null,

    val categoryName: kotlin.String? = null,

    val criteriaId: kotlin.Long? = null,

    val currencyCode: kotlin.String? = null,

    val expenseAccount: kotlin.Long? = null,

    val expenseAccountCode: kotlin.String? = null,

    val expenseAccountName: kotlin.String? = null,

    val historyId: kotlin.Long? = null,

    val liabilityAccountCode: kotlin.String? = null,

    val liabilityAccountName: kotlin.String? = null,

    val liablityAccount: kotlin.Long? = null,

    val officeId: kotlin.Long? = null,

    val officeName: kotlin.String? = null,

    val overdueInDays: kotlin.Long? = null,

    @Contextual
    val percentage: java.math.BigDecimal? = null,

    val productId: kotlin.Long? = null,

    val productName: kotlin.String? = null

)

