/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param score
 * @param valueFrom
 * @param valueTo
 */

@Serializable
data class LookupTableEntry(

    val score: kotlin.Double? = null,

    val valueFrom: kotlin.Int? = null,

    val valueTo: kotlin.Int? = null

)

