/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param parameters
 * @param subtype
 * @param type
 * @param wildcardSubtype
 * @param wildcardType
 */

@Serializable
data class MediaType(

    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    val subtype: kotlin.String? = null,

    val type: kotlin.String? = null,

    val wildcardSubtype: kotlin.Boolean? = null,

    val wildcardType: kotlin.Boolean? = null

)

