/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param clientId
 * @param createdById
 * @param createdByUsername
 * @param createdOn
 * @param depositAccountId
 * @param groupId
 * @param id
 * @param loanId
 * @param loanTransactionId
 * @param note
 * @param noteType
 * @param savingAccountId
 * @param updatedById
 * @param updatedByUsername
 * @param updatedOn
 */

@Serializable
data class NoteData(

    val clientId: kotlin.Long? = null,

    val createdById: kotlin.Long? = null,

    val createdByUsername: kotlin.String? = null,

    @Contextual
    val createdOn: java.time.OffsetDateTime? = null,

    val depositAccountId: kotlin.Long? = null,

    val groupId: kotlin.Long? = null,

    val id: kotlin.Long? = null,

    val loanId: kotlin.Long? = null,

    val loanTransactionId: kotlin.Long? = null,

    val note: kotlin.String? = null,

    val noteType: EnumOptionData? = null,

    val savingAccountId: kotlin.Long? = null,

    val updatedById: kotlin.Long? = null,

    val updatedByUsername: kotlin.String? = null,

    @Contextual
    val updatedOn: java.time.OffsetDateTime? = null

)

