/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param children
 * @param externalId
 * @param hierarchy
 * @param id
 * @param name
 * @param new
 * @param openingDate
 * @param openingLocalDate
 * @param parent
 */

@Serializable
data class Office(

    val children: kotlin.collections.List<Office>? = null,

    val externalId: ExternalId? = null,

    val hierarchy: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    @Contextual
    val openingDate: java.time.LocalDate? = null,

    @Contextual
    val openingLocalDate: java.time.LocalDate? = null,

    val parent: Office? = null

)

