/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param page
 * @param request
 * @param propertySize
 * @param sorts
 */

@Serializable
data class PagedRequestExternalAssetOwnerSearchRequest(

    val page: kotlin.Int? = null,

    val request: ExternalAssetOwnerSearchRequest? = null,

    val propertySize: kotlin.Int? = null,

    val sorts: kotlin.collections.List<SortOrder>? = null

)

