/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param offset
 * @param pageNumber
 * @param pageSize
 * @param paged
 * @param sort
 * @param unpaged
 */

@Serializable
data class Pageable(

    val offset: kotlin.Long? = null,

    val pageNumber: kotlin.Int? = null,

    val pageSize: kotlin.Int? = null,

    val paged: kotlin.Boolean? = null,

    val sort: Sort? = null,

    val unpaged: kotlin.Boolean? = null

)

