/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dateFormat
 * @param dateTimeFormat
 * @param locale
 * @param localeObject
 * @param page
 * @param request
 * @param propertySize
 * @param sorts
 */

@Serializable
data class PagedLocalRequestAdvancedQueryRequest(

    val dateFormat: kotlin.String? = null,

    val dateTimeFormat: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val localeObject: PagedLocalRequestAdvancedQueryDataLocaleObject? = null,

    val page: kotlin.Int? = null,

    val request: AdvancedQueryRequest? = null,

    val propertySize: kotlin.Int? = null,

    val sorts: kotlin.collections.List<SortOrder>? = null

)

