/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param codeName
 * @param description
 * @param id
 * @param isCashPayment
 * @param isSystemDefined
 * @param name
 * @param position
 */

@Serializable
data class PaymentTypeData(

    val codeName: kotlin.String? = null,

    val description: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val isCashPayment: kotlin.Boolean? = null,

    val isSystemDefined: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val position: kotlin.Int? = null

)

