/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param loanId
 * @param paymentTypeId
 * @param receiptNumber
 * @param transactionAmount
 */

@Serializable
data class PostCollectionSheetBulkRepaymentTransactions(

    val loanId: kotlin.Long? = null,

    val paymentTypeId: kotlin.Long? = null,

    val receiptNumber: kotlin.Long? = null,

    val transactionAmount: kotlin.Double? = null

)

