/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostGLCLosuresRequest
 *
 * @param closingDate
 * @param comments
 * @param dateFormat
 * @param locale
 * @param officeId
 */

@Serializable
data class PostGlClosuresRequest(

    @Contextual
    val closingDate: java.time.LocalDate? = null,

    val comments: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val officeId: kotlin.Long? = null

)

