/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostResourceTypeResourceIdNotesRequest
 *
 * @param note
 */

@Serializable
data class PostResourceTypeResourceIdNotesRequest(

    val note: kotlin.String? = null

)

