/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dateFormat
 * @param fromDate
 * @param interestRate
 * @param locale
 */

@Serializable
data class PostFloatingRatesRatePeriods(

    val dateFormat: kotlin.String? = null,

    val fromDate: kotlin.String? = null,

    val interestRate: kotlin.Double? = null,

    val locale: kotlin.String? = null

)

