/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PostLoansLoanIdScheduleResponse
 *
 * @param changes
 * @param loanId
 */

@Serializable
data class PostLoansLoanIdScheduleResponse(

    val changes: PostLoanChanges? = null,

    val loanId: kotlin.Long? = null

)

