/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PostLoansResponse
 *
 * @param clientId
 * @param currency
 * @param loanId
 * @param loanTermInDays
 * @param officeId
 * @param periods
 * @param resourceExternalId
 * @param resourceId
 * @param totalFeeChargesCharged
 * @param totalInterestCharged
 * @param totalOutstanding
 * @param totalPenaltyChargesCharged
 * @param totalPrincipalDisbursed
 * @param totalPrincipalExpected
 * @param totalPrincipalPaid
 * @param totalRepayment
 * @param totalRepaymentExpected
 * @param totalWaived
 * @param totalWrittenOff
 */

@Serializable
data class PostLoansResponse(

    val clientId: kotlin.Long? = null,

    val currency: GetLoansLoanIdCurrency? = null,

    val loanId: kotlin.Long? = null,

    val loanTermInDays: kotlin.Int? = null,

    val officeId: kotlin.Long? = null,

    val periods: kotlin.collections.Set<PostLoansRepaymentSchedulePeriods>? = null,

    val resourceExternalId: kotlin.String? = null,

    val resourceId: kotlin.Long? = null,

    val totalFeeChargesCharged: kotlin.Long? = null,

    val totalInterestCharged: kotlin.Double? = null,

    val totalOutstanding: kotlin.Long? = null,

    val totalPenaltyChargesCharged: kotlin.Long? = null,

    val totalPrincipalDisbursed: kotlin.Long? = null,

    val totalPrincipalExpected: kotlin.Long? = null,

    val totalPrincipalPaid: kotlin.Long? = null,

    val totalRepayment: kotlin.Long? = null,

    val totalRepaymentExpected: kotlin.Double? = null,

    val totalWaived: kotlin.Long? = null,

    val totalWrittenOff: kotlin.Long? = null

)

