/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PostLoansLoanIdChanges
 *
 * @param approvedOnDate
 * @param dateFormat
 * @param locale
 * @param note
 * @param status
 */

@Serializable
data class PostLoansLoanIdChanges(

    val approvedOnDate: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val note: kotlin.String? = null,

    val status: PostLoansLoanIdStatus? = null

)

