/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostLoansLoanIdRequest
 *
 * @param actualDisbursementDate
 * @param approvedLoanAmount
 * @param approvedOnDate
 * @param assignmentDate
 * @param dateFormat
 * @param disbursementData List of PostLoansLoanIdDisbursementData
 * @param expectedDisbursementDate
 * @param externalId
 * @param fromLoanOfficerId
 * @param locale
 * @param note
 * @param paymentTypeId
 * @param rejectedOnDate
 * @param toLoanOfficerId
 * @param transactionAmount
 * @param unassignedDate
 * @param withdrawnOnDate
 */

@Serializable
data class PostLoansLoanIdRequest(

    val actualDisbursementDate: kotlin.String? = null,

    @Contextual
    val approvedLoanAmount: java.math.BigDecimal? = null,

    val approvedOnDate: kotlin.String? = null,

    val assignmentDate: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val disbursementData: kotlin.collections.List<PostLoansLoanIdDisbursementData>? = null,

    val expectedDisbursementDate: kotlin.String? = null,

    val externalId: kotlin.String? = null,

    val fromLoanOfficerId: kotlin.Int? = null,

    val locale: kotlin.String? = null,

    val note: kotlin.String? = null,

    val paymentTypeId: kotlin.Int? = null,

    val rejectedOnDate: kotlin.String? = null,

    val toLoanOfficerId: kotlin.Int? = null,

    @Contextual
    val transactionAmount: java.math.BigDecimal? = null,

    val unassignedDate: kotlin.String? = null,

    val withdrawnOnDate: kotlin.String? = null

)

