/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostAccountNumberFormatsRequest
 *
 * @param accountType
 * @param prefixType
 */

@Serializable
data class PostAccountNumberFormatsRequest(

    val accountType: kotlin.Long? = null,

    val prefixType: kotlin.Long? = null

)

