/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PostInterestRateChartsChartIdChartSlabsRequest
 *
 * @param annualInterestRate
 * @param description
 * @param fromPeriod
 * @param incentives
 * @param locale
 * @param periodType
 * @param toPeriod
 */

@Serializable
data class PostInterestRateChartsChartIdChartSlabsRequest(

    val annualInterestRate: kotlin.Double? = null,

    val description: kotlin.String? = null,

    val fromPeriod: kotlin.Int? = null,

    val incentives: kotlin.collections.Set<PostInterestRateChartsChartIdChartSlabsIncentives>? = null,

    val locale: kotlin.String? = null,

    val periodType: kotlin.Int? = null,

    val toPeriod: kotlin.Int? = null

)

