/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostCentersCenterIdRequest
 *
 * @param closureDate
 * @param closureReasonId
 * @param dateFormat
 * @param locale
 */

@Serializable
data class PostCentersCenterIdRequest(

    val closureDate: kotlin.String? = null,

    val closureReasonId: kotlin.Long? = null,

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null

)

