/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostInterestRateChartsRequest
 *
 * @param dateFormat
 * @param description
 * @param fromDate
 * @param locale
 * @param name
 * @param type
 */

@Serializable
data class PostInterestRateChartsRequest(

    val dateFormat: kotlin.String? = null,

    val description: kotlin.String? = null,

    val fromDate: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val name: kotlin.String? = null,

    val type: kotlin.String? = null

)

