/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostClientCollateralRequest
 *
 * @param collateralId
 * @param locale
 * @param quantity
 */

@Serializable
data class PostClientCollateralRequest(

    val collateralId: kotlin.Long? = null,

    val locale: kotlin.String? = null,

    @Contextual
    val quantity: java.math.BigDecimal? = null

)

