/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostAccountingRulesRequest
 *
 * @param accountToCredit
 * @param accountToDebit
 * @param description
 * @param name
 * @param officeId
 */

@Serializable
data class PostAccountingRulesRequest(

    val accountToCredit: kotlin.Long? = null,

    val accountToDebit: kotlin.Long? = null,

    val description: kotlin.String? = null,

    val name: kotlin.String? = null,

    val officeId: kotlin.Long? = null

)

