/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostRecurringDepositAccountsRequest
 *
 * @param clientId
 * @param dateFormat
 * @param depositAmount
 * @param depositPeriod
 * @param depositPeriodFrequencyId
 * @param isCalendarInherited
 * @param locale
 * @param mandatoryRecommendedDepositAmount
 * @param productId
 * @param recurringFrequency
 * @param recurringFrequencyType
 * @param submittedOnDate
 */

@Serializable
data class PostRecurringDepositAccountsRequest(

    val clientId: kotlin.Long? = null,

    val dateFormat: kotlin.String? = null,

    val depositAmount: kotlin.Float? = null,

    val depositPeriod: kotlin.Int? = null,

    val depositPeriodFrequencyId: kotlin.Int? = null,

    val isCalendarInherited: kotlin.Boolean? = null,

    val locale: kotlin.String? = null,

    val mandatoryRecommendedDepositAmount: kotlin.Long? = null,

    val productId: kotlin.Long? = null,

    val recurringFrequency: kotlin.Int? = null,

    val recurringFrequencyType: kotlin.Int? = null,

    val submittedOnDate: kotlin.String? = null

)

