/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostLoansLoanIdChargesChargeIdRequest
 *
 * @param accountNumber
 * @param amount
 * @param bankNumber
 * @param chargeId
 * @param checkNumber
 * @param dateFormat
 * @param dueDate
 * @param externalId
 * @param installmentNumber
 * @param locale
 * @param note
 * @param paymentTypeId
 * @param receiptNumber
 * @param routingCode
 * @param transactionDate
 */

@Serializable
data class PostLoansLoanIdChargesChargeIdRequest(

    val accountNumber: kotlin.String? = null,

    val amount: kotlin.Double? = null,

    val bankNumber: kotlin.String? = null,

    val chargeId: kotlin.Long? = null,

    val checkNumber: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val dueDate: kotlin.String? = null,

    val externalId: kotlin.String? = null,

    val installmentNumber: kotlin.Long? = null,

    val locale: kotlin.String? = null,

    val note: kotlin.String? = null,

    val paymentTypeId: kotlin.Long? = null,

    val receiptNumber: kotlin.String? = null,

    val routingCode: kotlin.String? = null,

    val transactionDate: kotlin.String? = null

)

