/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param approvedByUserId
 * @param approvedOnDate
 * @param dateFormat
 * @param locale
 */

@Serializable
data class PostUpdateRescheduleLoanChanges(

    val approvedByUserId: kotlin.Long? = null,

    val approvedOnDate: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null

)

