/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostChargesRequest
 *
 * @param active
 * @param amount
 * @param chargeAppliesTo
 * @param chargeCalculationType
 * @param chargePaymentMode
 * @param chargeTimeType
 * @param currencyCode
 * @param locale
 * @param monthDayFormat
 * @param name
 * @param penalty
 */

@Serializable
data class PostChargesRequest(

    val active: kotlin.Boolean? = null,

    val amount: kotlin.Double? = null,

    val chargeAppliesTo: kotlin.Int? = null,

    val chargeCalculationType: kotlin.Int? = null,

    val chargePaymentMode: kotlin.Int? = null,

    val chargeTimeType: kotlin.Int? = null,

    val currencyCode: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val monthDayFormat: kotlin.String? = null,

    val name: kotlin.String? = null,

    val penalty: kotlin.Boolean? = null

)

