/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostSavingsAccountTransactionsRequest
 *
 * @param dateFormat
 * @param lienAllowed
 * @param locale
 * @param paymentTypeId
 * @param reasonForBlock
 * @param transactionAmount
 * @param transactionDate
 */

@Serializable
data class PostSavingsAccountTransactionsRequest(

    val dateFormat: kotlin.String? = null,

    val lienAllowed: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val paymentTypeId: kotlin.Int? = null,

    val reasonForBlock: kotlin.String? = null,

    @Contextual
    val transactionAmount: java.math.BigDecimal? = null,

    val transactionDate: kotlin.String? = null

)

