/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostSelfLoansLoanIdRequest
 *
 * @param dateFormat
 * @param locale
 * @param note
 * @param withdrawnOnDate
 */

@Serializable
data class PostSelfLoansLoanIdRequest(

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val note: kotlin.String? = null,

    val withdrawnOnDate: kotlin.String? = null

)

