/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostSurveySurveyNameApptableIdRequest
 *
 * @param date
 * @param dateFormat
 * @param locale
 * @param ppiBusinessoccupationCdQ3Businessoccupation
 * @param ppiFloortypeCdQ5Floortype
 * @param ppiFryingpansCdQ10Fryingpans
 * @param ppiHabitableroomsCdQ4Habitablerooms
 * @param ppiHighestschoolCdQ2Highestschool
 * @param ppiHouseholdMembersCdQ1Householdmembers
 * @param ppiIronsCdQ7Irons
 * @param ppiLightingsourceCdQ6Lightingsource
 * @param ppiMosquitonetsCdQ8Mosquitonets
 * @param ppiTowelsCdQ9Towels
 */

@Serializable
data class PostSurveySurveyNameApptableIdRequest(

    @Contextual
    val date: java.time.OffsetDateTime? = null,

    @Contextual
    val dateFormat: java.time.OffsetDateTime? = null,

    val locale: kotlin.String? = null,

    val ppi_businessoccupation_cd_q3_businessoccupation: kotlin.Long? = null,

    val ppi_floortype_cd_q5_floortype: kotlin.Long? = null,

    val ppi_fryingpans_cd_q10_fryingpans: kotlin.Long? = null,

    val ppi_habitablerooms_cd_q4_habitablerooms: kotlin.Long? = null,

    val ppi_highestschool_cd_q2_highestschool: kotlin.Long? = null,

    val ppi_household_members_cd_q1_householdmembers: kotlin.Long? = null,

    val ppi_irons_cd_q7_irons: kotlin.Long? = null,

    val ppi_lightingsource_cd_q6_lightingsource: kotlin.Long? = null,

    val ppi_mosquitonets_cd_q8_mosquitonets: kotlin.Long? = null,

    val ppi_towels_cd_q9_towels: kotlin.Long? = null

)

