/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostProvisioningEntriesRequest
 *
 * @param createjournalentries
 * @param date
 * @param dateFormat
 * @param propertyEntries
 * @param locale
 * @param provisioningentry
 */

@Serializable
data class PostProvisioningEntriesRequest(

    val createjournalentries: kotlin.String? = null,

    val date: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val propertyEntries: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val provisioningentry: kotlin.String? = null

)

