/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostReportMailingJobsRequest
 *
 * @param dateFormat
 * @param description
 * @param emailMessage
 * @param emailRecipients
 * @param emailSubject
 * @param isActive
 * @param locale
 * @param name
 * @param recurrence
 * @param startDateTime
 * @param stretchyReportId
 * @param stretchyReportParamMap
 */

@Serializable
data class PostReportMailingJobsRequest(

    val dateFormat: kotlin.String? = null,

    val description: kotlin.String? = null,

    val emailMessage: kotlin.String? = null,

    val emailRecipients: kotlin.String? = null,

    val emailSubject: kotlin.String? = null,

    val isActive: kotlin.Boolean? = null,

    val locale: kotlin.String? = null,

    val name: kotlin.String? = null,

    val recurrence: kotlin.String? = null,

    @Contextual
    val startDateTime: java.time.OffsetDateTime? = null,

    val stretchyReportId: kotlin.Long? = null,

    val stretchyReportParamMap: kotlin.String? = null

)

