/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostClientsRequest
 *
 * @param activationDate
 * @param active
 * @param address Address requests
 * @param datatables List of PostClientsDatatable
 * @param dateFormat
 * @param dateOfBirth
 * @param emailAddress
 * @param externalId
 * @param firstname
 * @param fullname
 * @param groupId
 * @param lastname
 * @param legalFormId
 * @param locale
 * @param middlename
 * @param mobileNo
 * @param officeId
 */

@Serializable
data class PostClientsRequest(

    val activationDate: kotlin.String? = null,

    val active: kotlin.Boolean? = null,

    val address: kotlin.collections.List<PostClientsAddressRequest>? = null,

    val datatables: kotlin.collections.List<PostClientsDatatable>? = null,

    val dateFormat: kotlin.String? = null,

    @Contextual
    val dateOfBirth: java.time.LocalDate? = null,

    val emailAddress: kotlin.String? = null,

    val externalId: kotlin.String? = null,

    val firstname: kotlin.String? = null,

    val fullname: kotlin.String? = null,

    val groupId: kotlin.Long? = null,

    val lastname: kotlin.String? = null,

    val legalFormId: kotlin.Long? = null,

    val locale: kotlin.String? = null,

    val middlename: kotlin.String? = null,

    val mobileNo: kotlin.String? = null,

    val officeId: kotlin.Long? = null

)

