/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostDelinquencyRangeRequest
 *
 * @param classification
 * @param locale
 * @param maximumAgeDays
 * @param minimumAgeDays
 */

@Serializable
data class PostDelinquencyRangeRequest(

    val classification: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val maximumAgeDays: kotlin.Int? = null,

    val minimumAgeDays: kotlin.Int? = null

)

