/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * List of PostClientsDatatable
 *
 * @param `data`
 * @param registeredTableName
 */

@Serializable
data class PostClientsDatatable(

    val data: kotlin.collections.Map<kotlin.String, @Contextual kotlin.Any>? = null,

    val registeredTableName: kotlin.String? = null

)

