/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PostInitiateTransferRequest
 *
 * @param dateFormat
 * @param locale
 * @param ownerExternalId
 * @param purchasePriceRatio
 * @param settlementDate
 * @param transferExternalId
 */

@Serializable
data class PostInitiateTransferRequest(

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val ownerExternalId: kotlin.String? = null,

    val purchasePriceRatio: kotlin.String? = null,

    val settlementDate: kotlin.String? = null,

    val transferExternalId: kotlin.String? = null

)

