/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostHolidaysRequest
 *
 * @param dateFormat
 * @param description
 * @param fromDate
 * @param locale
 * @param name
 * @param offices
 * @param repaymentsRescheduledTo
 * @param toDate
 */

@Serializable
data class PostHolidaysRequest(

    val dateFormat: kotlin.String? = null,

    val description: kotlin.String? = null,

    @Contextual
    val fromDate: java.time.LocalDate? = null,

    val locale: kotlin.String? = null,

    val name: kotlin.String? = null,

    val offices: kotlin.collections.List<PostHolidaysRequestOffices>? = null,

    @Contextual
    val repaymentsRescheduledTo: java.time.LocalDate? = null,

    @Contextual
    val toDate: java.time.LocalDate? = null

)

