/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PostAccountsTypeRequest
 *
 * @param allowDividendCalculationForInactiveClients
 * @param applicationDate
 * @param charges
 * @param clientId
 * @param dateFormat
 * @param externalId
 * @param locale
 * @param lockinPeriodFrequency
 * @param lockinPeriodFrequencyType
 * @param minimumActivePeriod
 * @param minimumActivePeriodFrequencyType
 * @param productId
 * @param requestedShares
 * @param savingsAccountId
 * @param submittedDate
 */

@Serializable
data class PostAccountsTypeRequest(

    val allowDividendCalculationForInactiveClients: kotlin.Boolean? = null,

    val applicationDate: kotlin.String? = null,

    val charges: kotlin.collections.Set<PostAccountsCharges>? = null,

    val clientId: kotlin.Long? = null,

    val dateFormat: kotlin.String? = null,

    val externalId: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val lockinPeriodFrequency: kotlin.Int? = null,

    val lockinPeriodFrequencyType: kotlin.Int? = null,

    val minimumActivePeriod: kotlin.Int? = null,

    val minimumActivePeriodFrequencyType: kotlin.Int? = null,

    val productId: kotlin.Long? = null,

    val requestedShares: kotlin.Int? = null,

    val savingsAccountId: kotlin.Long? = null,

    val submittedDate: kotlin.String? = null

)

