/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param `data`
 * @param registeredTableName
 */

@Serializable
data class PostSelfLoansDatatables(

    val data: PostSelfLoansData? = null,

    val registeredTableName: kotlin.String? = null

)

