/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dueDate
 * @param feeChargesDue
 * @param feeChargesOutstanding
 * @param period
 * @param principalDisbursed
 * @param principalLoanBalanceOutstanding
 * @param totalActualCostOfLoanForPeriod
 * @param totalDueForPeriod
 * @param totalOriginalDueForPeriod
 * @param totalOutstandingForPeriod
 * @param totalOverdue
 */

@Serializable
data class PostLoansRepaymentSchedulePeriods(

    @Contextual
    val dueDate: java.time.LocalDate? = null,

    val feeChargesDue: kotlin.Long? = null,

    val feeChargesOutstanding: kotlin.Long? = null,

    val period: kotlin.Int? = null,

    val principalDisbursed: kotlin.Long? = null,

    val principalLoanBalanceOutstanding: kotlin.Long? = null,

    val totalActualCostOfLoanForPeriod: kotlin.Long? = null,

    val totalDueForPeriod: kotlin.Long? = null,

    val totalOriginalDueForPeriod: kotlin.Long? = null,

    val totalOutstandingForPeriod: kotlin.Long? = null,

    val totalOverdue: kotlin.Long? = null

)

