/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PostCollateralManagementProductRequest
 *
 * @param basePrice
 * @param currency
 * @param name
 * @param pctToBase
 * @param quality
 * @param unitType
 */

@Serializable
data class PostCollateralManagementProductRequest(

    @Contextual
    val basePrice: java.math.BigDecimal? = null,

    val currency: kotlin.String? = null,

    val name: kotlin.String? = null,

    @Contextual
    val pctToBase: java.math.BigDecimal? = null,

    val quality: kotlin.String? = null,

    val unitType: kotlin.String? = null

)

