/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param categoryId
 * @param categoryName
 * @param expenseAccount
 * @param expenseCode
 * @param expenseName
 * @param id
 * @param liabilityAccount
 * @param liabilityCode
 * @param liabilityName
 * @param maxAge
 * @param minAge
 * @param provisioningPercentage
 */

@Serializable
data class ProvisioningCriteriaDefinitionData(

    val categoryId: kotlin.Long? = null,

    val categoryName: kotlin.String? = null,

    val expenseAccount: kotlin.Long? = null,

    val expenseCode: kotlin.String? = null,

    val expenseName: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val liabilityAccount: kotlin.Long? = null,

    val liabilityCode: kotlin.String? = null,

    val liabilityName: kotlin.String? = null,

    val maxAge: kotlin.Long? = null,

    val minAge: kotlin.Long? = null,

    @Contextual
    val provisioningPercentage: java.math.BigDecimal? = null

)

