/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param createdById
 * @param createdDate
 * @param createdUser
 * @param id
 * @param journalEntry
 * @param modifiedById
 * @param modifiedUser
 * @param provisioningEntries
 * @param reservedAmount
 */

@Serializable
data class ProvisioningEntryData(

    val createdById: kotlin.Long? = null,

    @Contextual
    val createdDate: java.time.LocalDate? = null,

    val createdUser: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val journalEntry: kotlin.Boolean? = null,

    val modifiedById: kotlin.Long? = null,

    val modifiedUser: kotlin.String? = null,

    val provisioningEntries: kotlin.collections.List<LoanProductProvisioningEntryData>? = null,

    @Contextual
    val reservedAmount: java.math.BigDecimal? = null

)

