/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutAccountsTypeAccountIdRequest
 *
 * @param applicationDate
 * @param dateFormat
 * @param locale
 * @param requestedShares
 */

@Serializable
data class PutAccountsTypeAccountIdRequest(

    val applicationDate: kotlin.String? = null,

    val dateFormat: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val requestedShares: kotlin.Int? = null

)

