/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutClientsClientIdIdentifiersIdentifierIdRequest
 *
 * @param description
 * @param documentKey
 * @param documentTypeId
 */

@Serializable
data class PutClientsClientIdIdentifiersIdentifierIdRequest(

    val description: kotlin.String? = null,

    val documentKey: kotlin.String? = null,

    val documentTypeId: kotlin.Long? = null

)

