/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutClientClientIdAddressesRequest
 *
 * @param addressId
 * @param street
 */

@Serializable
data class PutClientClientIdAddressesRequest(

    val addressId: kotlin.Long? = null,

    val street: kotlin.String? = null

)

