/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutExternalServiceRequest
 *
 * @param password
 * @param username
 */

@Serializable
data class PutExternalServiceRequest(

    val password: kotlin.String? = null,

    val username: kotlin.String? = null

)

