/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PutEntityTypeEntityIdDocumentsResponse
 *
 * @param changes
 * @param resourceId
 * @param resourceIdentifier
 */

@Serializable
data class PutEntityTypeEntityIdDocumentsResponse(

    @Contextual
    val changes: kotlin.Any? = null,

    val resourceId: kotlin.Long? = null,

    val resourceIdentifier: kotlin.String? = null

)

