/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PutFloatingRatesFloatingRateIdRequest
 *
 * @param isActive
 * @param isBaseLendingRate
 * @param name
 * @param ratePeriods
 */

@Serializable
data class PutFloatingRatesFloatingRateIdRequest(

    val isActive: kotlin.Boolean? = null,

    val isBaseLendingRate: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val ratePeriods: kotlin.collections.Set<PostFloatingRatesRatePeriods>? = null

)

