/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutGLAccountsRequest
 *
 * @param description
 * @param disabled
 * @param glCode
 * @param manualEntriesAllowed
 * @param name
 * @param parentId
 * @param tagId
 * @param type
 * @param usage
 */

@Serializable
data class PutGLAccountsRequest(

    val description: kotlin.String? = null,

    val disabled: kotlin.Boolean? = null,

    val glCode: kotlin.String? = null,

    val manualEntriesAllowed: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val parentId: kotlin.Long? = null,

    val tagId: kotlin.Long? = null,

    val type: kotlin.Int? = null,

    val usage: kotlin.Int? = null

)

