/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Event
import org.openapitools.client.models.Field

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Serializable

/**
 * PutHookRequest
 *
 * @param config
 * @param displayName
 * @param events
 * @param isActive
 * @param name
 * @param templateId
 */

@Serializable
data class PutHookRequest(

    val config: kotlin.collections.List<Field>? = null,

    val displayName: kotlin.String? = null,

    val events: kotlin.collections.List<Event>? = null,

    val isActive: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val templateId: kotlin.Long? = null

)

