/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param config
 * @param displayName
 * @param events
 */

@Serializable
data class PutHookResponseChangesSwagger(

    val config: kotlin.collections.List<Field>? = null,

    val displayName: kotlin.String? = null,

    val events: kotlin.collections.List<Event>? = null

)

