/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutInterestRateChartsChartIdRequest
 *
 * @param description
 * @param name
 */

@Serializable
data class PutInterestRateChartsChartIdRequest(

    val description: kotlin.String? = null,

    val name: kotlin.String? = null

)

