/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dateFormat
 * @param expectedDisbursementDate
 * @param interestType
 * @param isEqualAmortization
 * @param locale
 * @param netDisbursalAmount
 * @param principal
 */

@Serializable
data class PutLoansLoanIdDisbursementData(

    val dateFormat: kotlin.String? = null,

    val expectedDisbursementDate: kotlin.String? = null,

    val interestType: kotlin.Int? = null,

    val isEqualAmortization: kotlin.Boolean? = null,

    val locale: kotlin.String? = null,

    @Contextual
    val netDisbursalAmount: java.math.BigDecimal? = null,

    @Contextual
    val principal: java.math.BigDecimal? = null

)

