/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PutLoansLoanIdCollateralsCollateralIdResponse
 *
 * @param changes
 * @param loanId
 * @param resourceId
 */

@Serializable
data class PutLoansLoanIdCollateralsCollateralIdResponse(

    val changes: PutLoansLoandIdCollateralsCollateralIdRequest? = null,

    val loanId: kotlin.Long? = null,

    val resourceId: kotlin.Long? = null

)

