/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PutProvisioningCriteriaResponse
 *
 * @param changes
 * @param resourceId
 */

@Serializable
data class PutProvisioningCriteriaResponse(

    val changes: PutProvisioningCriteriaResponseChanges? = null,

    val resourceId: kotlin.Long? = null

)

