/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PutProvisioningCriteriaRequest
 *
 * @param criteriaName
 * @param loanProducts
 * @param provisioningcriteria
 */

@Serializable
data class PutProvisioningCriteriaRequest(

    val criteriaName: kotlin.String? = null,

    val loanProducts: kotlin.collections.List<LoanProductData>? = null,

    val provisioningcriteria: kotlin.collections.List<ProvisioningCriteriaDefinitionData>? = null

)

