/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutProductsTypeProductIdRequest
 *
 * @param description
 * @param locale
 * @param unitPrice
 */

@Serializable
data class PutProductsTypeProductIdRequest(

    val description: kotlin.String? = null,

    val locale: kotlin.String? = null,

    val unitPrice: kotlin.Double? = null

)

