/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param permissions
 */

@Serializable
data class PutRolesRoleIdPermissionsResponsePermissionsChanges(

    val permissions: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

)

