/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutRecurringDepositAccountsAccountIdRequest
 *
 * @param depositAmount
 * @param locale
 */

@Serializable
data class PutRecurringDepositAccountsAccountIdRequest(

    val depositAmount: kotlin.Int? = null,

    val locale: kotlin.String? = null

)

