/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param reportName
 * @param reportParameters
 */

@Serializable
data class PutReportResponseChanges(

    val reportName: kotlin.String? = null,

    val reportParameters: kotlin.collections.List<@Contextual kotlin.Any>? = null

)

