/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PutResourceTypeResourceIdNotesNoteIdResponse
 *
 * @param changes
 * @param clientId
 * @param officeId
 * @param resourceId
 */

@Serializable
data class PutResourceTypeResourceIdNotesNoteIdResponse(

    val changes: PutNotesChanges? = null,

    val clientId: kotlin.Long? = null,

    val officeId: kotlin.Long? = null,

    val resourceId: kotlin.Int? = null

)

