/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutStaffRequest
 *
 * @param externalId
 * @param isLoanOfficer
 */

@Serializable
data class PutStaffRequest(

    val externalId: kotlin.String? = null,

    val isLoanOfficer: kotlin.Boolean? = null

)

