/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutSavingsAccountsAccountIdRequest
 *
 * @param locale
 * @param nominalAnnualInterestRate
 */

@Serializable
data class PutSavingsAccountsAccountIdRequest(

    val locale: kotlin.String? = null,

    val nominalAnnualInterestRate: kotlin.Double? = null

)

