/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutSelfBeneficiariesTPTBeneficiaryIdRequest
 *
 * @param name
 * @param transferLimit
 */

@Serializable
data class PutSelfBeneficiariesTPTBeneficiaryIdRequest(

    val name: kotlin.String? = null,

    val transferLimit: kotlin.Int? = null

)

