/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 * PutSelfLoansLoanIdRequest
 *
 * @param amortizationType
 * @param dateFormat
 * @param expectedDisbursementDate
 * @param interestCalculationPeriodType
 * @param interestRatePerPeriod
 * @param interestType
 * @param loanTermFrequency
 * @param loanTermFrequencyType
 * @param locale
 * @param numberOfRepayments
 * @param principal
 * @param productId
 * @param repaymentEvery
 * @param repaymentFrequencyType
 * @param transactionProcessingStrategyCode
 */

@Serializable
data class PutSelfLoansLoanIdRequest(

    val amortizationType: kotlin.Int? = null,

    val dateFormat: kotlin.String? = null,

    val expectedDisbursementDate: kotlin.String? = null,

    val interestCalculationPeriodType: kotlin.Int? = null,

    val interestRatePerPeriod: kotlin.Int? = null,

    val interestType: kotlin.Int? = null,

    val loanTermFrequency: kotlin.Int? = null,

    val loanTermFrequencyType: kotlin.Int? = null,

    val locale: kotlin.String? = null,

    val numberOfRepayments: kotlin.Int? = null,

    val principal: kotlin.Long? = null,

    val productId: kotlin.Int? = null,

    val repaymentEvery: kotlin.Int? = null,

    val repaymentFrequencyType: kotlin.Int? = null,

    val transactionProcessingStrategyCode: kotlin.String? = null

)

