/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PutTellersRequest
 *
 * @param dateFormat
 * @param description
 * @param endDate
 * @param locale
 * @param name
 * @param officeId
 * @param startDate
 * @param status
 */

@Serializable
data class PutTellersRequest(

    val dateFormat: kotlin.String? = null,

    val description: kotlin.String? = null,

    @Contextual
    val endDate: java.time.LocalDate? = null,

    val locale: kotlin.String? = null,

    val name: kotlin.String? = null,

    val officeId: kotlin.Long? = null,

    @Contextual
    val startDate: java.time.LocalDate? = null,

    val status: PutTellersRequest.Status? = null

) {

    /**
     *
     *
     * Values: INVALID,PENDING,ACTIVE,INACTIVE,CLOSED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "INVALID")
        INVALID("INVALID"),

        @Json(name = "PENDING")
        PENDING("PENDING"),

        @Json(name = "ACTIVE")
        ACTIVE("ACTIVE"),

        @Json(name = "INACTIVE")
        INACTIVE("INACTIVE"),

        @Json(name = "CLOSED")
        CLOSED("CLOSED");
    }

}

