/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * PutTellersTellerIdCashiersCashierIdRequest
 *
 * @param dateFormat
 * @param description
 * @param endDate
 * @param isFullDay
 * @param locale
 * @param staffId
 * @param startDate
 */

@Serializable
data class PutTellersTellerIdCashiersCashierIdRequest(

    val dateFormat: kotlin.String? = null,

    val description: kotlin.String? = null,

    @Contextual
    val endDate: java.time.LocalDate? = null,

    val isFullDay: kotlin.Boolean? = null,

    val locale: kotlin.String? = null,

    val staffId: kotlin.Long? = null,

    @Contextual
    val startDate: java.time.LocalDate? = null

)

