/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dateFormat
 * @param description
 * @param endDate
 * @param locale
 */

@Serializable
data class PutTellersTellerIdCashiersCashierIdResponseChanges(

    val dateFormat: kotlin.String? = null,

    val description: kotlin.String? = null,

    @Contextual
    val endDate: java.time.LocalDate? = null,

    val locale: kotlin.String? = null

)

