/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param endDate
 * @param id
 * @param taxComponentId
 */

@Serializable
data class PutTaxesGroupTaxComponents(

    val endDate: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val taxComponentId: kotlin.Long? = null

)

