/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 * PutWorkingDaysRequest
 *
 * @param extendTermForDailyRepayments
 * @param locale
 * @param recurrence
 * @param repaymentRescheduleType
 */

@Serializable
data class PutWorkingDaysRequest(

    val extendTermForDailyRepayments: kotlin.Boolean? = null,

    val locale: kotlin.String? = null,

    val recurrence: kotlin.String? = null,

    val repaymentRescheduleType: EnumOptionData? = null

)

