/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param approveUser
 * @param createdBy
 * @param createdDate
 * @param id
 * @param lastModifiedBy
 * @param lastModifiedDate
 * @param name
 * @param new
 * @param percentage
 * @param productApply
 */

@Serializable
data class Rate(

    val active: kotlin.Boolean? = null,

    val approveUser: AppUser? = null,

    val createdBy: kotlin.Long? = null,

    @Contextual
    val createdDate: java.time.OffsetDateTime? = null,

    val id: kotlin.Long? = null,

    val lastModifiedBy: kotlin.Long? = null,

    @Contextual
    val lastModifiedDate: java.time.OffsetDateTime? = null,

    val name: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    @Contextual
    val percentage: java.math.BigDecimal? = null,

    val productApply: kotlin.Int? = null

)

