/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param active
 * @param id
 * @param name
 * @param percentage
 * @param productApply
 */

@Serializable
data class RateData(

    val active: kotlin.Boolean? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    @Contextual
    val percentage: java.math.BigDecimal? = null,

    val productApply: EnumOptionData? = null

)

