/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param endDateTime
 * @param errorLog
 * @param errorMessage
 * @param id
 * @param reportMailingJobId
 * @param startDateTime
 * @param status
 */

@Serializable
data class ReportMailingJobRunHistoryData(

    @Contextual
    val endDateTime: java.time.OffsetDateTime? = null,

    val errorLog: kotlin.String? = null,

    val errorMessage: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val reportMailingJobId: kotlin.Long? = null,

    @Contextual
    val startDateTime: java.time.OffsetDateTime? = null,

    val status: kotlin.String? = null

)

