/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Permission

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param disabled 
 * @param enabled 
 * @param id 
 * @param name 
 * @param new 
 * @param permissions 
 */

@Serializable
data class Role (

    val disabled: kotlin.Boolean? = null,

    val enabled: kotlin.Boolean? = null,

    val id: kotlin.Long? = null,

    val name: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    val permissions: kotlin.collections.List<Permission>? = null

) {


}

