/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param columnHeaders
 * @param `data`
 */

@Serializable
data class RunReportsResponse(

    val columnHeaders: kotlin.collections.List<ResultsetColumnHeaderData>? = null,

    val data: kotlin.collections.List<ResultsetRowData>? = null

)

