/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.math.BigDecimal

/**
 *
 *
 * @param accrualBasedAccountingEnabled
 * @param allowOverdraft
 * @param cashBasedAccountingEnabled
 * @param currency
 * @param depositAccountType
 * @param id
 * @param interestCalculationDaysInYearType
 * @param interestCalculationType
 * @param interestCompoundingPeriodType
 * @param interestPostingPeriodType
 * @param lockinPeriodFrequency
 * @param lockinPeriodFrequencyType
 * @param maxAllowedLienLimit
 * @param minRequiredBalance
 * @param minRequiredOpeningBalance
 * @param name
 * @param nominalAnnualInterestRate
 * @param overdraftLimit
 * @param periodicAccrualAccounting
 * @param upfrontAccrualAccounting
 * @param withdrawalFeeForTransfers
 */

@Serializable
data class SavingsProductData(

    val accrualBasedAccountingEnabled: kotlin.Boolean? = null,

    val allowOverdraft: kotlin.Boolean? = null,

    val cashBasedAccountingEnabled: kotlin.Boolean? = null,

    val currency: CurrencyData? = null,

    val depositAccountType: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val interestCalculationDaysInYearType: EnumOptionData? = null,

    val interestCalculationType: EnumOptionData? = null,

    val interestCompoundingPeriodType: EnumOptionData? = null,

    val interestPostingPeriodType: EnumOptionData? = null,

    val lockinPeriodFrequency: kotlin.Int? = null,

    val lockinPeriodFrequencyType: EnumOptionData? = null,

    @Contextual
    val maxAllowedLienLimit: BigDecimal? = null,

    @Contextual
    val minRequiredBalance: BigDecimal? = null,

    @Contextual
    val minRequiredOpeningBalance: BigDecimal? = null,

    val name: kotlin.String? = null,

    @Contextual
    val nominalAnnualInterestRate: BigDecimal? = null,

    @Contextual
    val overdraftLimit: BigDecimal? = null,

    val periodicAccrualAccounting: kotlin.Boolean? = null,

    val upfrontAccrualAccounting: kotlin.Boolean? = null,

    val withdrawalFeeForTransfers: kotlin.Boolean? = null

)

