/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param block
 * @param blockCredit
 * @param blockDebit
 * @param code
 * @param dormant
 * @param escheat
 * @param id
 * @param inactive
 * @param none
 * @param `value`
 */

@Serializable
data class SavingsAccountSubStatusEnumData(

    val block: kotlin.Boolean? = null,

    val blockCredit: kotlin.Boolean? = null,

    val blockDebit: kotlin.Boolean? = null,

    val code: kotlin.String? = null,

    val dormant: kotlin.Boolean? = null,

    val escheat: kotlin.Boolean? = null,

    val id: kotlin.Long? = null,

    val inactive: kotlin.Boolean? = null,

    val none: kotlin.Boolean? = null,

    val value: kotlin.String? = null

)

