/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.math.BigDecimal
import java.time.LocalDate

/**
 *
 *
 * @param accountId
 * @param amount
 * @param amountOrPercentage
 * @param amountOutstanding
 * @param amountPaid
 * @param amountPercentageAppliedTo
 * @param amountWaived
 * @param amountWrittenOff
 * @param annualFee
 * @param chargeCalculationType
 * @param chargeData
 * @param chargeId
 * @param chargeOptions
 * @param chargeTimeType
 * @param currency
 * @param dueDate
 * @param feeCharge
 * @param feeInterval
 * @param feeOnMonthDay
 * @param freeWithdrawalChargeFrequency
 * @param id
 * @param inactivationDate
 * @param isActive
 * @param isFreeWithdrawal
 * @param name
 * @param penalty
 * @param percentage
 * @param restartFrequency
 * @param restartFrequencyEnum
 * @param savingsActivation
 * @param withdrawalFee
 */

@Serializable
data class SavingsAccountChargeData(

    val accountId: kotlin.Long? = null,

    @Contextual
    val amount: BigDecimal? = null,

    @Contextual
    val amountOrPercentage: BigDecimal? = null,

    @Contextual
    val amountOutstanding: BigDecimal? = null,

    @Contextual
    val amountPaid: BigDecimal? = null,

    @Contextual
    val amountPercentageAppliedTo: BigDecimal? = null,

    @Contextual
    val amountWaived: BigDecimal? = null,

    @Contextual
    val amountWrittenOff: BigDecimal? = null,

    val annualFee: kotlin.Boolean? = null,

    val chargeCalculationType: EnumOptionData? = null,

    val chargeData: ChargeData? = null,

    val chargeId: kotlin.Long? = null,

    val chargeOptions: kotlin.collections.List<ChargeData>? = null,

    val chargeTimeType: EnumOptionData? = null,

    val currency: CurrencyData? = null,

    @Contextual
    val dueDate: LocalDate? = null,

    val feeCharge: kotlin.Boolean? = null,

    val feeInterval: kotlin.Int? = null,

    val feeOnMonthDay: ChargeFeeOnMonthDay? = null,

    val freeWithdrawalChargeFrequency: kotlin.Int? = null,

    val id: kotlin.Long? = null,

    @Contextual
    val inactivationDate: LocalDate? = null,

    val isActive: kotlin.Boolean? = null,

    val isFreeWithdrawal: kotlin.Boolean? = null,

    val name: kotlin.String? = null,

    val penalty: kotlin.Boolean? = null,

    @Contextual
    val percentage: BigDecimal? = null,

    val restartFrequency: kotlin.Int? = null,

    val restartFrequencyEnum: kotlin.Int? = null,

    val savingsActivation: kotlin.Boolean? = null,

    val withdrawalFee: kotlin.Boolean? = null

)

