/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.math.BigDecimal

/**
 *
 *
 * @param amount
 * @param chargeId
 * @param feeCharge
 * @param penaltyCharge
 * @param savingsAccountChargeData
 */

@Serializable
data class SavingsAccountChargesPaidByData(

    @Contextual
    val amount: BigDecimal? = null,

    val chargeId: kotlin.Long? = null,

    val feeCharge: kotlin.Boolean? = null,

    val penaltyCharge: kotlin.Boolean? = null,

    val savingsAccountChargeData: SavingsAccountChargeData? = null

)

