/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param createdOn
 * @param questionId
 * @param responseId
 * @param `value`
 */

@Serializable
data class ScorecardValue(

    @Contextual
    val createdOn: java.time.OffsetDateTime? = null,

    val questionId: kotlin.Long? = null,

    val responseId: kotlin.Long? = null,

    val value: kotlin.Int? = null

)

