/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param clientId
 * @param id
 * @param scorecardValues
 * @param surveyId
 * @param surveyName
 * @param userId
 * @param username
 */

@Serializable
data class ScorecardData(

    val clientId: kotlin.Long? = null,

    val id: kotlin.Long? = null,

    val scorecardValues: kotlin.collections.List<ScorecardValue>? = null,

    val surveyId: kotlin.Long? = null,

    val surveyName: kotlin.String? = null,

    val userId: kotlin.Long? = null,

    val username: kotlin.String? = null

)

