/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param amount
 * @param comments
 * @param commentsChanged
 * @param glAccountId
 * @param glAccountIdChanged
 * @param glAmountChanged
 * @param parametersPassedInRequest
 */

@Serializable
data class SingleDebitOrCreditEntryCommand(

    @Contextual
    val amount: java.math.BigDecimal? = null,

    val comments: kotlin.String? = null,

    val commentsChanged: kotlin.Boolean? = null,

    val glAccountId: kotlin.Long? = null,

    val glAccountIdChanged: kotlin.Boolean? = null,

    val glAmountChanged: kotlin.Boolean? = null,

    val parametersPassedInRequest: kotlin.collections.Set<kotlin.String>? = null

)

