/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param campaignName
 * @param campaignStatus
 * @param campaignType
 * @param id
 * @param lastTriggerDate
 * @param message
 * @param nextTriggerDate
 * @param notification
 * @param paramValue
 * @param recurrence
 * @param recurrenceStartDate
 * @param reportName
 * @param runReportId
 */

@Serializable
data class SmsCampaignData(

    val campaignName: kotlin.String? = null,

    val campaignStatus: EnumOptionData? = null,

    val campaignType: EnumOptionData? = null,

    val id: kotlin.Long? = null,

    @Contextual
    val lastTriggerDate: java.time.LocalDate? = null,

    val message: kotlin.String? = null,

    @Contextual
    val nextTriggerDate: java.time.OffsetDateTime? = null,

    val notification: kotlin.Boolean? = null,

    val paramValue: kotlin.String? = null,

    val recurrence: kotlin.String? = null,

    @Contextual
    val recurrenceStartDate: java.time.OffsetDateTime? = null,

    val reportName: kotlin.String? = null,

    val runReportId: kotlin.Long? = null

)

