/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param empty
 * @param sorted
 * @param unsorted
 */

@Serializable
data class Sort(

    val empty: kotlin.Boolean? = null,

    val sorted: kotlin.Boolean? = null,

    val unsorted: kotlin.Boolean? = null

)

