/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Image
import org.openapitools.client.models.Office

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param active 
 * @param displayName 
 * @param emailAddress 
 * @param externalId 
 * @param firstname 
 * @param id 
 * @param image 
 * @param joiningDate 
 * @param lastname 
 * @param loanOfficer 
 * @param mobileNo 
 * @param new 
 * @param notActive 
 * @param notLoanOfficer 
 * @param office 
 * @param organisationalRoleParentStaff 
 * @param organisationalRoleType 
 */

@Serializable
data class Staff (

    val active: kotlin.Boolean? = null,

    val displayName: kotlin.String? = null,

    val emailAddress: kotlin.String? = null,

    val externalId: kotlin.String? = null,

    val firstname: kotlin.String? = null,

    val id: kotlin.Long? = null,

    val image: Image? = null,

    @Contextual
    val joiningDate: java.time.LocalDate? = null,

    val lastname: kotlin.String? = null,

    val loanOfficer: kotlin.Boolean? = null,

    val mobileNo: kotlin.String? = null,

    val new: kotlin.Boolean? = null,

    val notActive: kotlin.Boolean? = null,

    val notLoanOfficer: kotlin.Boolean? = null,

    val office: Office? = null,

    val organisationalRoleParentStaff: Staff? = null,

    val organisationalRoleType: kotlin.Int? = null

) {


}

