/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param mapperkey
 * @param mapperorder
 * @param mappervalue
 * @param new
 */

@Serializable
data class TemplateMapper(

    val id: kotlin.Long? = null,

    val mapperkey: kotlin.String? = null,

    val mapperorder: kotlin.Int? = null,

    val mappervalue: kotlin.String? = null,

    val new: kotlin.Boolean? = null

)

