/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.Serializable

/**
 *
 *
 * @param noteData
 * @param paymentDetails
 * @param transactionId
 * @param transactionType
 */

@Serializable
data class TransactionDetailData(

    val noteData: NoteData? = null,

    val paymentDetails: PaymentDetailData? = null,

    val transactionId: kotlin.Long? = null,

    val transactionType: TransactionTypeEnumData? = null

)

