/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountNo
 * @param amount
 * @param bankName
 * @param date
 */

@Serializable
data class UpdateChangesResponse(

    val accountNo: kotlin.Long? = null,

    @Contextual
    val amount: java.math.BigDecimal? = null,

    val bankName: kotlin.String? = null,

    @Contextual
    val date: java.time.LocalDate? = null

)

